# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech


# NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the file manually.

# API Wrapper methods for Blueprints
# To use these methods without modification, DR endpoint and token
# should be set as environment variables. This will automatically
# happen when you call `datarobot::ConnectToDataRobot()`.



#' GetBlueprintChart
#'
#' Retrieve a blueprint chart by blueprint id.
#'
#' Retrieve a blueprint chart by blueprint id.
#'
#' @seealso The method ProjectsBlueprintsBlueprintChartList in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
GetBlueprintChart <- function(project, blueprintId, ...) {
  projectId <- ValidateProject(project)
  routeString <- UrlJoin("projects", projectId, "blueprints", blueprintId, "blueprintChart")
  # start of generated addition
  # end of generated addition
  return(DataRobotGET(routeString, simplifyDataFrame = FALSE))
}

#' GetBlueprintDocumentation
#'
#' Retrieve blueprint tasks documentation.
#'
#' Retrieve blueprint tasks documentation.
#'
#' @seealso The method ProjectsBlueprintsBlueprintDocsList in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
GetBlueprintDocumentation <- function(project, blueprintId, ...) {
  projectId <- ValidateProject(project)
  routeString <- UrlJoin("projects", projectId, "blueprints", blueprintId, "blueprintDocs")
  # start of generated addition
  # end of generated addition
  docs <- DataRobotGET(routeString, simplifyDataFrame = FALSE)
}

#' ListBlueprints
#'
#' List blueprints
#'
#' List appropriate blueprints for the project.
#'
#' @seealso The method ProjectsBlueprintsList in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
ListBlueprints <- function(project, ...) {
  projectId <- ValidateProject(project)
  routeString <- UrlJoin("projects", projectId, "blueprints")
  # start of generated addition
  # end of generated addition
  blueprints <- DataRobotGET(routeString, simplify = FALSE)
  blueprintList <- lapply(blueprints, function(blueprint) {
    blueprint$blueprintId <- blueprint$id
    blueprint$id <- NULL
    blueprint
  })
  blueprintList <- lapply(blueprintList, as.dataRobotBlueprint)
  class(blueprintList) <- c("listOfBlueprints", "listSubclass")
  blueprintList
}

#' GetBlueprint
#'
#' Retrieve a blueprint by its ID.
#'
#' Retrieve a blueprint by its ID.
#'
#' @seealso The method ProjectsBlueprintsRetrieve in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
GetBlueprint <- function(project, blueprintId, ...) {
  projectId <- ValidateProject(project)
  routeString <- UrlJoin("projects", projectId, "blueprints", blueprintId)
  # start of generated addition
  # end of generated addition
  blueprint <- DataRobotGET(routeString, simplifyDataFrame = FALSE)
  return(as.dataRobotBlueprint(blueprint))
}

#' GetModelBlueprintChart
#'
#' Retrieve a reduced model blueprint chart by model id.
#'
#' Retrieve a reduced model blueprint chart by model id. The model blueprint charts are reduced from the full blueprint charts to show only those sections of the blueprint that were actually used in the model, given the selected featurelist.
#'
#' @seealso The method ProjectsModelsBlueprintChartList in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
GetModelBlueprintChart <- function(project, modelId, ...) {
  projectId <- ValidateProject(project)
  routeString <- UrlJoin("projects", projectId, "models", modelId, "blueprintChart")
  # start of generated addition
  # end of generated addition
  return(DataRobotGET(routeString, simplifyDataFrame = FALSE))
}

#' GetModelBlueprintDocumentation
#'
#' Retrieve task documentation for a reduced model blueprint.
#'
#' Retrieve task documentation for a reduced model blueprint. The model blueprint is reduced from the full blueprint to show only those sections of the blueprint that were actually used in the model, given the selected featurelist.
#'
#' @seealso The method ProjectsModelsBlueprintDocsList in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
GetModelBlueprintDocumentation <- function(project, modelId, ...) {
  projectId <- ValidateProject(project)
  routeString <- UrlJoin("projects", projectId, "models", modelId, "blueprintDocs")
  # start of generated addition
  # end of generated addition
  docs <- DataRobotGET(routeString, simplifyDataFrame = FALSE)
}

#' ListProjectsModelsLogs
#'
#' Retrieve an archive (tar.gz) of the logs produced and persisted by a model.
#'
#' Retrieve an archive (tar.gz) of the logs produced and persisted by a model. Note that only blueprints with custom tasks create persistent logs - this will not work with any other type of model.
#'
#' @seealso The method ProjectsModelsLogsList in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
ListProjectsModelsLogs <- function(modelId, projectId, ...) {
  return(datarobot.apicore::BlueprintsApi$new()$ProjectsModelsLogsList(modelId = modelId, projectId = projectId))
}

#' ListProjectsModelsTrainingArtifact
#'
#' Retrieve an archive (tar.gz) of the artifacts produced and persisted by a model.
#'
#' Retrieve an archive (tar.gz) of the artifacts produced and persisted by a model. Note that only blueprints with custom tasks create these artifacts - this will not work with any other type of model.
#'
#' @seealso The method ProjectsModelsTrainingArtifactList in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
ListProjectsModelsTrainingArtifact <- function(modelId, projectId, ...) {
  return(datarobot.apicore::BlueprintsApi$new()$ProjectsModelsTrainingArtifactList(modelId = modelId, projectId = projectId))
}

#' CreateUserBlueprintsBulkValidations
#'
#' Validate many user blueprints.
#'
#' Validate many user blueprints, optionally using a specific project. Any non-existent or inaccessible user blueprints will be ignored.
#'
#' @seealso The method UserBlueprintsBulkValidationsCreate in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
CreateUserBlueprintsBulkValidations <- function(userBlueprintIds, projectId, ...) {
  userBlueprintBulkValidationRequest <- datarobot.apicore::UserBlueprintBulkValidationRequest$new(userBlueprintIds = userBlueprintIds, projectId = projectId, validateParams = TRUE)
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsBulkValidationsCreate(userBlueprintBulkValidationRequest = userBlueprintBulkValidationRequest))
}

#' CreateUserBlueprints
#'
#' Create a user blueprint.
#'
#' Create a user blueprint
#'
#' @seealso The method UserBlueprintsCreate in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
CreateUserBlueprints <- function(blueprint, description, modelType, projectId, isInplaceEditor = FALSE, getDynamicLabels = FALSE, decompressedBlueprint = FALSE, saveToCatalog = TRUE, ...) {
  userBlueprintCreate <- datarobot.apicore::UserBlueprintCreate$new(blueprint = blueprint, isInplaceEditor = isInplaceEditor, getDynamicLabels = getDynamicLabels, decompressedBlueprint = decompressedBlueprint, description = description, modelType = modelType, projectId = projectId, saveToCatalog = saveToCatalog, validateParams = TRUE)
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsCreate(userBlueprintCreate = userBlueprintCreate))
}

#' DeleteUserBlueprints
#'
#' Delete a user blueprint.
#'
#' Delete a user blueprint, specified by the `userBlueprintId`.
#'
#' @seealso The method UserBlueprintsDelete in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
DeleteUserBlueprints <- function(userBlueprintId, ...) {
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsDelete(userBlueprintId = userBlueprintId))
}

#' DeleteManyUserBlueprints
#'
#' Delete user blueprints.
#'
#' Delete user blueprints, specified by `userBlueprintIds`.
#'
#' @seealso The method UserBlueprintsDeleteMany in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
DeleteManyUserBlueprints <- function(userBlueprintIds, ...) {
  userBlueprintsBulkDelete <- datarobot.apicore::UserBlueprintsBulkDelete$new(userBlueprintIds = userBlueprintIds, validateParams = TRUE)
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsDeleteMany(userBlueprintsBulkDelete = userBlueprintsBulkDelete))
}

#' CreateUserBlueprintsFromBlueprintId
#'
#' Clone a blueprint from a project.
#'
#' Clone a blueprint from a project.
#'
#' @seealso The method UserBlueprintsFromBlueprintIdCreate in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
CreateUserBlueprintsFromBlueprintId <- function(description, modelType, projectId, blueprintId, isInplaceEditor = FALSE, getDynamicLabels = FALSE, decompressedBlueprint = FALSE, saveToCatalog = TRUE, ...) {
  userBlueprintCreateFromBlueprintId <- datarobot.apicore::UserBlueprintCreateFromBlueprintId$new(isInplaceEditor = isInplaceEditor, getDynamicLabels = getDynamicLabels, decompressedBlueprint = decompressedBlueprint, description = description, modelType = modelType, projectId = projectId, blueprintId = blueprintId, saveToCatalog = saveToCatalog, validateParams = TRUE)
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsFromBlueprintIdCreate(userBlueprintCreateFromBlueprintId = userBlueprintCreateFromBlueprintId))
}

#' CreateUserBlueprintsFromCustomTaskVersionId
#'
#' Create a user blueprint from a single custom task.
#'
#' Create a user blueprint from a single custom task.
#'
#' @seealso The method UserBlueprintsFromCustomTaskVersionIdCreate in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
CreateUserBlueprintsFromCustomTaskVersionId <- function(customTaskVersionId, description, decompressedBlueprint = FALSE, saveToCatalog = TRUE, ...) {
  userBlueprintCreateFromCustomTaskVersionIdPayload <- datarobot.apicore::UserBlueprintCreateFromCustomTaskVersionIdPayload$new(decompressedBlueprint = decompressedBlueprint, customTaskVersionId = customTaskVersionId, description = description, saveToCatalog = saveToCatalog, validateParams = TRUE)
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsFromCustomTaskVersionIdCreate(userBlueprintCreateFromCustomTaskVersionIdPayload = userBlueprintCreateFromCustomTaskVersionIdPayload))
}

#' CreateUserBlueprintsFromUserBlueprintId
#'
#' Clone a user blueprint.
#'
#' Clone a user blueprint.
#'
#' @seealso The method UserBlueprintsFromUserBlueprintIdCreate in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
CreateUserBlueprintsFromUserBlueprintId <- function(userBlueprintId, description, modelType, projectId, isInplaceEditor = FALSE, getDynamicLabels = FALSE, decompressedBlueprint = FALSE, saveToCatalog = TRUE, ...) {
  userBlueprintCreateFromUserBlueprintId <- datarobot.apicore::UserBlueprintCreateFromUserBlueprintId$new(userBlueprintId = userBlueprintId, isInplaceEditor = isInplaceEditor, getDynamicLabels = getDynamicLabels, decompressedBlueprint = decompressedBlueprint, description = description, modelType = modelType, projectId = projectId, saveToCatalog = saveToCatalog, validateParams = TRUE)
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsFromUserBlueprintIdCreate(userBlueprintCreateFromUserBlueprintId = userBlueprintCreateFromUserBlueprintId))
}

#' ListUserBlueprintsInputTypes
#'
#' Retrieve input types.
#'
#' Retrieve the input types which can be used with User Blueprints.
#'
#' @seealso The method UserBlueprintsInputTypesList in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
ListUserBlueprintsInputTypes <- function(...) {
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsInputTypesList())
}

#' ListUserBlueprints
#'
#' List user blueprints.
#'
#' Fetch a list of the user blueprints the current user has access to
#'
#' @seealso The method UserBlueprintsList in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
ListUserBlueprints <- function(projectId, offset = 0, limit = 100, ...) {
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsList(offset = offset, limit = limit, projectId = projectId))
}

#' PatchUserBlueprints
#'
#' Update a user blueprint.
#'
#' Update a user blueprint
#'
#' @seealso The method UserBlueprintsPatch in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
PatchUserBlueprints <- function(blueprint, userBlueprintId, description, modelType, projectId, isInplaceEditor = FALSE, getDynamicLabels = FALSE, decompressedBlueprint = FALSE, saveToCatalog = TRUE, ...) {
  userBlueprintUpdate <- datarobot.apicore::UserBlueprintUpdate$new(blueprint = blueprint, isInplaceEditor = isInplaceEditor, getDynamicLabels = getDynamicLabels, decompressedBlueprint = decompressedBlueprint, description = description, modelType = modelType, projectId = projectId, saveToCatalog = saveToCatalog, validateParams = TRUE)
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsPatch(userBlueprintUpdate = userBlueprintUpdate, userBlueprintId = userBlueprintId))
}

#' CreateUserBlueprintsProjectBlueprints
#'
#' Add user blueprints to a project.
#'
#' Add a list of user blueprints, by id, to a specified (by id) project's repository.
#'
#' @seealso The method UserBlueprintsProjectBlueprintsCreate in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
CreateUserBlueprintsProjectBlueprints <- function(userBlueprintIds, projectId, deleteAfter = FALSE, describeFailures = FALSE, ...) {
  userBlueprintAddToMenu <- datarobot.apicore::UserBlueprintAddToMenu$new(deleteAfter = deleteAfter, userBlueprintIds = userBlueprintIds, describeFailures = describeFailures, projectId = projectId, validateParams = TRUE)
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsProjectBlueprintsCreate(userBlueprintAddToMenu = userBlueprintAddToMenu))
}

#' RetrieveUserBlueprints
#'
#' Retrieve a user blueprint.
#'
#' Retrieve a user blueprint
#'
#' @seealso The method UserBlueprintsRetrieve in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
RetrieveUserBlueprints <- function(userBlueprintId, projectId, isInplaceEditor = FALSE, getDynamicLabels = FALSE, decompressedBlueprint = FALSE, editMode = FALSE, ...) {
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsRetrieve(userBlueprintId = userBlueprintId, isInplaceEditor = isInplaceEditor, getDynamicLabels = getDynamicLabels, decompressedBlueprint = decompressedBlueprint, editMode = editMode, projectId = projectId))
}

#' ListUserBlueprintsSharedRoles
#'
#' Get a list of users, groups and organizations that have an access to this user blueprint
#'
#' Get a list of users, groups and organizations that have an access to this user blueprint
#'
#' @seealso The method UserBlueprintsSharedRolesList in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
ListUserBlueprintsSharedRoles <- function(userBlueprintId, shareRecipientType, name, id, offset = 0, limit = 10, ...) {
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsSharedRolesList(userBlueprintId = userBlueprintId, shareRecipientType = shareRecipientType, offset = offset, name = name, limit = limit, id = id))
}

#' PatchManyUserBlueprintsSharedRoles
#'
#' Share a user blueprint with a user, group, or organization
#'
#' Share a user blueprint with a user, group, or organization
#'
#' @seealso The method UserBlueprintsSharedRolesPatchMany in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
PatchManyUserBlueprintsSharedRoles <- function(userBlueprintId, roles, operation, ...) {
  sharedRolesUpdate <- datarobot.apicore::SharedRolesUpdate$new(roles = roles, operation = operation, validateParams = TRUE)
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsSharedRolesPatchMany(userBlueprintId = userBlueprintId, sharedRolesUpdate = sharedRolesUpdate))
}

#' CreateUserBlueprintsTaskParameters
#'
#' Validate task parameters.
#'
#' Validate that each value assigned to specified task parameters are valid.
#'
#' @seealso The method UserBlueprintsTaskParametersCreate in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
CreateUserBlueprintsTaskParameters <- function(taskCode, outputMethod, taskParameters, projectId, ...) {
  userBlueprintTaskParameterValidation <- datarobot.apicore::UserBlueprintTaskParameterValidation$new(taskCode = taskCode, outputMethod = outputMethod, taskParameters = taskParameters, projectId = projectId, validateParams = TRUE)
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsTaskParametersCreate(userBlueprintTaskParameterValidation = userBlueprintTaskParameterValidation))
}

#' ListUserBlueprintsTasks
#'
#' Retrieve tasks for blueprint construction.
#'
#' Retrieve the available tasks, organized into categories, which can be used to create or modify User Blueprints.
#'
#' @seealso The method UserBlueprintsTasksList in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
ListUserBlueprintsTasks <- function(userBlueprintId, blueprintId, projectId, ...) {
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsTasksList(userBlueprintId = userBlueprintId, blueprintId = blueprintId, projectId = projectId))
}

#' CreateUserBlueprintsValidations
#'
#' Validate a user blueprint.
#'
#' Validate a user blueprint
#'
#' @seealso The method UserBlueprintsValidationsCreate in [datarobot.apicore::BlueprintsApi], which this function wraps.
#' @family Blueprints
#' @export
CreateUserBlueprintsValidations <- function(blueprint, projectId, isInplaceEditor = FALSE, ...) {
  userBlueprintValidation <- datarobot.apicore::UserBlueprintValidation$new(blueprint = blueprint, isInplaceEditor = isInplaceEditor, projectId = projectId, validateParams = TRUE)
  return(datarobot.apicore::BlueprintsApi$new()$UserBlueprintsValidationsCreate(userBlueprintValidation = userBlueprintValidation))
}
