# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech


# NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the file manually.

# API Wrapper methods for Utilities
# To use these methods without modification, DR endpoint and token
# should be set as environment variables. This will automatically
# happen when you call `datarobot::ConnectToDataRobot()`.



#' CreateStringEncryptions
#'
#' Encrypt a string which DataRobot can decrypt.
#'
#' DataRobot does not store your credentials when accessing external data stores. Instead you first encrypt your sensitive information with DataRobot and then, when accessing those data stores, supply the encrypted credentials. DataRobot will decrypt your credentials and use them to establish a connection to your data store.
#'
#' @seealso The method StringEncryptionsCreate in [datarobot.apicore::UtilitiesApi], which this function wraps.
#' @family Utilities
#' @export
CreateStringEncryptions <- function(plainText, ...) {
  stringEncryption <- datarobot.apicore::StringEncryption$new(plainText = plainText, validateParams = TRUE)
  return(datarobot.apicore::UtilitiesApi$new()$StringEncryptionsCreate(stringEncryption = stringEncryption))
}
