# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AnomalyOverTimePlotsMetadataResponse
#'
#' @description AnomalyOverTimePlotsMetadataResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field backtestMetadata  list( \link{DatetimeTrendPlotsBacktestMetadata} ) An array of metadata information for each backtest. The array index of metadata object is the backtest index.
#'
#' @field backtestStatuses  list( \link{AccuracyOverTimePlotsStatus} ) An array of status information for each backtest. The array index of status object is the backtest index.
#'
#' @field holdoutMetadata  \link{DatetimeTrendPlotsBacktestMetadata}
#'
#' @field holdoutStatuses  \link{AccuracyOverTimePlotsStatus}
#'
#' @field resolutions  list( character ) An array of available time resolutions for which plots can be retrieved.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AnomalyOverTimePlotsMetadataResponse <- R6::R6Class(
  "AnomalyOverTimePlotsMetadataResponse",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(backtestMetadata = NULL, backtestStatuses = NULL, holdoutMetadata = NULL, holdoutStatuses = NULL, resolutions = NULL) {
      if (!is.null(`backtestMetadata`)) {
        stopifnot(is.vector(`backtestMetadata`))
      }
      if (!is.null(`backtestStatuses`)) {
        stopifnot(is.vector(`backtestStatuses`))
      }
      if (!is.null(`holdoutMetadata`)) {
        stopifnot(R6::is.R6(`holdoutMetadata`))
      }
      if (!is.null(`holdoutStatuses`)) {
        stopifnot(R6::is.R6(`holdoutStatuses`))
      }
      if (!is.null(`resolutions`)) {
        stopifnot(is.vector(`resolutions`))
      }
    }
  ),
  public = list(
    `backtestMetadata` = NULL,
    `backtestStatuses` = NULL,
    `holdoutMetadata` = NULL,
    `holdoutStatuses` = NULL,
    `resolutions` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param backtestMetadata An array of metadata information for each backtest. The array index of metadata object is the backtest index.
    #' @param backtestStatuses An array of status information for each backtest. The array index of status object is the backtest index.
    #' @param holdoutMetadata
    #' @param holdoutStatuses
    #' @param resolutions An array of available time resolutions for which plots can be retrieved.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`backtestMetadata` = NULL, `backtestStatuses` = NULL, `holdoutMetadata` = NULL, `holdoutStatuses` = NULL, `resolutions` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`backtestMetadata`, `backtestStatuses`, `holdoutMetadata`, `holdoutStatuses`, `resolutions`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(backtestMetadata, backtestStatuses, holdoutMetadata, holdoutStatuses, resolutions)
      }
      sapply(`backtestMetadata`, function(x) stopifnot(R6::is.R6(x)))
      sapply(`backtestStatuses`, function(x) stopifnot(R6::is.R6(x)))
      self$`holdoutMetadata` <- `holdoutMetadata`
      self$`holdoutStatuses` <- `holdoutStatuses`
      sapply(`resolutions`, function(x) stopifnot(is.character(x)))
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(backtestMetadata = self$`backtestMetadata`, backtestStatuses = self$`backtestStatuses`, holdoutMetadata = self$`holdoutMetadata`, holdoutStatuses = self$`holdoutStatuses`, resolutions = self$`resolutions`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`backtestMetadata`)) {
          sprintf(
            '"backtestMetadata":
            [%s]
',
            paste(sapply(self$`backtestMetadata`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`backtestStatuses`)) {
          sprintf(
            '"backtestStatuses":
            [%s]
',
            paste(sapply(self$`backtestStatuses`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`holdoutMetadata`)) {
          sprintf(
            '"holdoutMetadata":
          %s
        ',
            jsonlite::toJSON(self$`holdoutMetadata`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        },
        if (!is.null(self$`holdoutStatuses`)) {
          sprintf(
            '"holdoutStatuses":
          %s
        ',
            jsonlite::toJSON(self$`holdoutStatuses`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        },
        if (!is.null(self$`resolutions`)) {
          sprintf(
            '"resolutions":
              [%s]
            ',
            paste(unlist(lapply(self$`resolutions`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param AnomalyOverTimePlotsMetadataResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(AnomalyOverTimePlotsMetadataResponseJson, validateParams = FALSE) {
      AnomalyOverTimePlotsMetadataResponseObject <- jsonlite::fromJSON(AnomalyOverTimePlotsMetadataResponseJson)
      self$`backtestMetadata` <- ApiClient$new()$deserializeObj(AnomalyOverTimePlotsMetadataResponseObject$`backtestMetadata`, "array[DatetimeTrendPlotsBacktestMetadata]", loadNamespace("datarobot.apicore"))
      self$`backtestStatuses` <- ApiClient$new()$deserializeObj(AnomalyOverTimePlotsMetadataResponseObject$`backtestStatuses`, "array[AccuracyOverTimePlotsStatus]", loadNamespace("datarobot.apicore"))
      self$`holdoutMetadata` <- DatetimeTrendPlotsBacktestMetadata$new()$fromJSON(jsonlite::toJSON(AnomalyOverTimePlotsMetadataResponseObject$holdoutMetadata, auto_unbox = TRUE, digits = NA, null = "null"))
      self$`holdoutStatuses` <- AccuracyOverTimePlotsStatus$new()$fromJSON(jsonlite::toJSON(AnomalyOverTimePlotsMetadataResponseObject$holdoutStatuses, auto_unbox = TRUE, digits = NA, null = "null"))
      self$`resolutions` <- ApiClient$new()$deserializeObj(AnomalyOverTimePlotsMetadataResponseObject$`resolutions`, "array[character]", loadNamespace("datarobot.apicore"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
