# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ApplicationTypeConfigurationDeployment
#'
#' @description ApplicationTypeConfigurationDeployment Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field description  character [optional] A description of the deployment configuration
#'
#' @field internalName  character The internal name of this deployment
#'
#' @field name  character The name of this deployment
#'
#' @field targetTypes  list( character ) [optional] The type of the deployment
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ApplicationTypeConfigurationDeployment <- R6::R6Class(
  "ApplicationTypeConfigurationDeployment",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(description = NULL, internalName = NULL, name = NULL, targetTypes = NULL) {
      if (!is.null(`internalName`)) {
        stopifnot(is.character(`internalName`), length(`internalName`) == 1)
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
      }
      if (!is.null(`targetTypes`)) {
        stopifnot(is.vector(`targetTypes`))
      }
    }
  ),
  public = list(
    `description` = NULL,
    `internalName` = NULL,
    `name` = NULL,
    `targetTypes` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param description A description of the deployment configuration
    #' @param internalName The internal name of this deployment
    #' @param name The name of this deployment
    #' @param targetTypes The type of the deployment
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`internalName` = NULL, `name` = NULL, `description` = NULL, `targetTypes` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`internalName`, `name`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(description, internalName, name, targetTypes)
      }
      self$`description` <- `description`
      self$`internalName` <- `internalName`
      self$`name` <- `name`
      sapply(`targetTypes`, function(x) stopifnot(is.character(x)))
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(description = self$`description`, internalName = self$`internalName`, name = self$`name`, targetTypes = self$`targetTypes`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`description`)) {
          sprintf(
            '"description":
            "%s"
                  ',
            self$`description`
          )
        },
        if (!is.null(self$`internalName`)) {
          sprintf(
            '"internalName":
            "%s"
                  ',
            self$`internalName`
          )
        },
        if (!is.null(self$`name`)) {
          sprintf(
            '"name":
            "%s"
                  ',
            self$`name`
          )
        },
        if (!is.null(self$`targetTypes`)) {
          sprintf(
            '"targetTypes":
              [%s]
            ',
            paste(unlist(lapply(self$`targetTypes`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param ApplicationTypeConfigurationDeploymentJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(ApplicationTypeConfigurationDeploymentJson, validateParams = FALSE) {
      ApplicationTypeConfigurationDeploymentObject <- jsonlite::fromJSON(ApplicationTypeConfigurationDeploymentJson)
      self$`description` <- ApplicationTypeConfigurationDeploymentObject$`description`
      self$`internalName` <- ApplicationTypeConfigurationDeploymentObject$`internalName`
      self$`name` <- ApplicationTypeConfigurationDeploymentObject$`name`
      self$`targetTypes` <- ApiClient$new()$deserializeObj(ApplicationTypeConfigurationDeploymentObject$`targetTypes`, "array[character]", loadNamespace("datarobot.apicore"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
