# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Autopilot
#'
#' @description Autopilot Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field command  character If &#x60;start&#x60;, will unpause the autopilot and run queued jobs if workers are available.  If &#x60;stop&#x60;, will pause the autopilot so no new jobs will be started.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Autopilot <- R6::R6Class(
  "Autopilot",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`command` = NULL) {
      if (!is.null(`command`)) {
        stopifnot(is.character(`command`), length(`command`) == 1)
      }
    }
  ),
  public = list(
    `command` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param command If &#x60;start&#x60;, will unpause the autopilot and run queued jobs if workers are available.  If &#x60;stop&#x60;, will pause the autopilot so no new jobs will be started.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`command` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`command`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(command)
      }
      self$`command` <- `command`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(command = self$`command`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`command`)) {
          sprintf(
            '"command":
            "%s"
                  ',
            self$`command`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param AutopilotJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(AutopilotJson, validateParams = FALSE) {
      AutopilotObject <- jsonlite::fromJSON(AutopilotJson)
      self$`command` <- AutopilotObject$`command`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
