# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AutopilotStart
#'
#' @description AutopilotStart Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field autopilotClusterList  list( integer ) [optional] Optional. A list of integers where each value will be used as the number of clusters in Autopilot model(s) for unsupervised clustering projects. Cannot be specified unless unsupervisedMode is true and unsupervisedType is set to &#39;clustering&#39;.
#'
#' @field blendBestModels  character [optional] Blend best models during Autopilot run. This option is not supported in SHAP-only mode or for multilabel projects.
#'
#' @field considerBlendersInRecommendation  character [optional] Include blenders when selecting a model to prepare for deployment in an Autopilot Run. This option is not supported in SHAP-only mode or for multilabel projects.
#'
#' @field featurelistId  character The ID of a featurelist that should be used for autopilot.
#'
#' @field mode  character [optional] The autopilot mode.
#'
#' @field prepareModelForDeployment  character [optional] Prepare model for deployment during Autopilot run. The preparation includes creating reduced feature list models, retraining best model on higher sample size, computing insights and assigning \&quot;RECOMMENDED FOR DEPLOYMENT\&quot; label.
#'
#' @field runLeakageRemovedFeatureList  character [optional] Run Autopilot on Leakage Removed feature list (if exists).
#'
#' @field scoringCodeOnly  character [optional] Keep only models that can be converted to scorable java code during Autopilot run.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AutopilotStart <- R6::R6Class(
  "AutopilotStart",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`autopilotClusterList` = NULL, `blendBestModels` = NULL, `considerBlendersInRecommendation` = NULL, `featurelistId` = NULL, `mode` = NULL, `prepareModelForDeployment` = NULL, `runLeakageRemovedFeatureList` = NULL, `scoringCodeOnly` = NULL) {
      if (!is.null(`featurelistId`)) {
        stopifnot(is.character(`featurelistId`), length(`featurelistId`) == 1)
      }
      if (!is.null(`autopilotClusterList`) && length(`autopilotClusterList`) > 0) {
        stopifnot(is.vector(`autopilotClusterList`), sapply(`autopilotClusterList`, is.numeric))
      }
      if (!is.null(`blendBestModels`)) {
        stopifnot(is.logical(`blendBestModels`), length(`blendBestModels`) == 1)
      }
      if (!is.null(`considerBlendersInRecommendation`)) {
        stopifnot(is.logical(`considerBlendersInRecommendation`), length(`considerBlendersInRecommendation`) == 1)
      }
      if (!is.null(`mode`)) {
        stopifnot(is.character(`mode`), length(`mode`) == 1)
      }
      if (!is.null(`prepareModelForDeployment`)) {
        stopifnot(is.logical(`prepareModelForDeployment`), length(`prepareModelForDeployment`) == 1)
      }
      if (!is.null(`runLeakageRemovedFeatureList`)) {
        stopifnot(is.logical(`runLeakageRemovedFeatureList`), length(`runLeakageRemovedFeatureList`) == 1)
      }
      if (!is.null(`scoringCodeOnly`)) {
        stopifnot(is.logical(`scoringCodeOnly`), length(`scoringCodeOnly`) == 1)
      }
    }
  ),
  public = list(
    `autopilotClusterList` = NULL,
    `blendBestModels` = NULL,
    `considerBlendersInRecommendation` = NULL,
    `featurelistId` = NULL,
    `mode` = NULL,
    `prepareModelForDeployment` = NULL,
    `runLeakageRemovedFeatureList` = NULL,
    `scoringCodeOnly` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param autopilotClusterList Optional. A list of integers where each value will be used as the number of clusters in Autopilot model(s) for unsupervised clustering projects. Cannot be specified unless unsupervisedMode is true and unsupervisedType is set to &#39;clustering&#39;.
    #' @param blendBestModels Blend best models during Autopilot run. This option is not supported in SHAP-only mode or for multilabel projects.
    #' @param considerBlendersInRecommendation Include blenders when selecting a model to prepare for deployment in an Autopilot Run. This option is not supported in SHAP-only mode or for multilabel projects.
    #' @param featurelistId The ID of a featurelist that should be used for autopilot.
    #' @param mode The autopilot mode.
    #' @param prepareModelForDeployment Prepare model for deployment during Autopilot run. The preparation includes creating reduced feature list models, retraining best model on higher sample size, computing insights and assigning \&quot;RECOMMENDED FOR DEPLOYMENT\&quot; label.
    #' @param runLeakageRemovedFeatureList Run Autopilot on Leakage Removed feature list (if exists).
    #' @param scoringCodeOnly Keep only models that can be converted to scorable java code during Autopilot run.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`featurelistId` = NULL, `autopilotClusterList` = NULL, `blendBestModels` = NULL, `considerBlendersInRecommendation` = NULL, `mode` = "auto", `prepareModelForDeployment` = NULL, `runLeakageRemovedFeatureList` = NULL, `scoringCodeOnly` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`featurelistId`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(autopilotClusterList, blendBestModels, considerBlendersInRecommendation, featurelistId, mode, prepareModelForDeployment, runLeakageRemovedFeatureList, scoringCodeOnly)
      }
      self$`autopilotClusterList` <- `autopilotClusterList`
      self$`blendBestModels` <- `blendBestModels`
      self$`considerBlendersInRecommendation` <- `considerBlendersInRecommendation`
      self$`featurelistId` <- `featurelistId`
      self$`mode` <- `mode`
      self$`prepareModelForDeployment` <- `prepareModelForDeployment`
      self$`runLeakageRemovedFeatureList` <- `runLeakageRemovedFeatureList`
      self$`scoringCodeOnly` <- `scoringCodeOnly`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(autopilotClusterList = self$`autopilotClusterList`, blendBestModels = self$`blendBestModels`, considerBlendersInRecommendation = self$`considerBlendersInRecommendation`, featurelistId = self$`featurelistId`, mode = self$`mode`, prepareModelForDeployment = self$`prepareModelForDeployment`, runLeakageRemovedFeatureList = self$`runLeakageRemovedFeatureList`, scoringCodeOnly = self$`scoringCodeOnly`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`autopilotClusterList`)) {
          sprintf(
            '"autopilotClusterList":
            [%s]
                  ',
            paste(unlist(lapply(self$`autopilotClusterList`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`blendBestModels`)) {
          sprintf(
            '"blendBestModels":
            %s
                  ',
            tolower(self$`blendBestModels`)
          )
        },
        if (!is.null(self$`considerBlendersInRecommendation`)) {
          sprintf(
            '"considerBlendersInRecommendation":
            %s
                  ',
            tolower(self$`considerBlendersInRecommendation`)
          )
        },
        if (!is.null(self$`featurelistId`)) {
          sprintf(
            '"featurelistId":
            "%s"
                  ',
            self$`featurelistId`
          )
        },
        if (!is.null(self$`mode`)) {
          sprintf(
            '"mode":
            "%s"
                  ',
            self$`mode`
          )
        },
        if (!is.null(self$`prepareModelForDeployment`)) {
          sprintf(
            '"prepareModelForDeployment":
            %s
                  ',
            tolower(self$`prepareModelForDeployment`)
          )
        },
        if (!is.null(self$`runLeakageRemovedFeatureList`)) {
          sprintf(
            '"runLeakageRemovedFeatureList":
            %s
                  ',
            tolower(self$`runLeakageRemovedFeatureList`)
          )
        },
        if (!is.null(self$`scoringCodeOnly`)) {
          sprintf(
            '"scoringCodeOnly":
            %s
                  ',
            tolower(self$`scoringCodeOnly`)
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param AutopilotStartJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(AutopilotStartJson, validateParams = FALSE) {
      AutopilotStartObject <- jsonlite::fromJSON(AutopilotStartJson)
      self$`autopilotClusterList` <- ApiClient$new()$deserializeObj(AutopilotStartObject$`autopilotClusterList`, "array[integer]", loadNamespace("datarobot.apicore"))
      self$`blendBestModels` <- AutopilotStartObject$`blendBestModels`
      self$`considerBlendersInRecommendation` <- AutopilotStartObject$`considerBlendersInRecommendation`
      self$`featurelistId` <- AutopilotStartObject$`featurelistId`
      self$`mode` <- AutopilotStartObject$`mode`
      self$`prepareModelForDeployment` <- AutopilotStartObject$`prepareModelForDeployment`
      self$`runLeakageRemovedFeatureList` <- AutopilotStartObject$`runLeakageRemovedFeatureList`
      self$`scoringCodeOnly` <- AutopilotStartObject$`scoringCodeOnly`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
