# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AverageModelMetricsValues
#'
#' @description AverageModelMetricsValues Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character Metric name.
#'
#' @field numLabelsUsedInCalculation  integer Number of labels that were taken into account in the calculation of metric averages
#'
#' @field values  list( numeric ) Metric values at given thresholds.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AverageModelMetricsValues <- R6::R6Class(
  "AverageModelMetricsValues",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`name` = NULL, `numLabelsUsedInCalculation` = NULL, `values` = NULL) {
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
      }
      if (!is.null(`numLabelsUsedInCalculation`)) {
        stopifnot(is.numeric(`numLabelsUsedInCalculation`), length(`numLabelsUsedInCalculation`) == 1)
      }
      if (!is.null(`values`)) {
        stopifnot(is.vector(`values`))
      }
    }
  ),
  public = list(
    `name` = NULL,
    `numLabelsUsedInCalculation` = NULL,
    `values` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param name Metric name.
    #' @param numLabelsUsedInCalculation Number of labels that were taken into account in the calculation of metric averages
    #' @param values Metric values at given thresholds.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`name` = NULL, `numLabelsUsedInCalculation` = NULL, `values` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`name`, `numLabelsUsedInCalculation`, `values`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(name, numLabelsUsedInCalculation, values)
      }
      self$`name` <- `name`
      self$`numLabelsUsedInCalculation` <- `numLabelsUsedInCalculation`
      sapply(`values`, function(x) stopifnot(is.character(x)))
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(name = self$`name`, numLabelsUsedInCalculation = self$`numLabelsUsedInCalculation`, values = self$`values`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
          sprintf(
            '"name":
            "%s"
                  ',
            self$`name`
          )
        },
        if (!is.null(self$`numLabelsUsedInCalculation`)) {
          sprintf(
            '"numLabelsUsedInCalculation":
            %d
                  ',
            self$`numLabelsUsedInCalculation`
          )
        },
        if (!is.null(self$`values`)) {
          sprintf(
            '"values":
            [%s]
                  ',
            paste(unlist(lapply(self$`values`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param AverageModelMetricsValuesJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(AverageModelMetricsValuesJson, validateParams = FALSE) {
      AverageModelMetricsValuesObject <- jsonlite::fromJSON(AverageModelMetricsValuesJson)
      self$`name` <- AverageModelMetricsValuesObject$`name`
      self$`numLabelsUsedInCalculation` <- AverageModelMetricsValuesObject$`numLabelsUsedInCalculation`
      self$`values` <- ApiClient$new()$deserializeObj(AverageModelMetricsValuesObject$`values`, "array[numeric]", loadNamespace("datarobot.apicore"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
