# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CombinedModelResponse
#'
#' @description CombinedModelResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field combinedModelId  character The ID of combined model.
#'
#' @field isActiveCombinedModel  character Indicates whether this model is the active one in segmented modeling project.
#'
#' @field modelCategory  character Indicates what kind of model this is. Will be &#x60;&#x60;combined&#x60;&#x60; for combined models.
#'
#' @field projectId  character The ID of the project.
#'
#' @field segmentationTaskId  character The ID of the segmentation task used to generate this combined model.
#'
#' @field segments  list( \link{SegmentProjectModelResponse} ) Information for each segment. Maps each segment to the project and model used for it.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CombinedModelResponse <- R6::R6Class(
  "CombinedModelResponse",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`combinedModelId` = NULL, `isActiveCombinedModel` = NULL, `modelCategory` = NULL, `projectId` = NULL, `segmentationTaskId` = NULL, `segments` = NULL) {
      if (!is.null(`combinedModelId`)) {
        stopifnot(is.character(`combinedModelId`), length(`combinedModelId`) == 1)
      }
      if (!is.null(`isActiveCombinedModel`)) {
        stopifnot(is.logical(`isActiveCombinedModel`), length(`isActiveCombinedModel`) == 1)
      }
      if (!is.null(`modelCategory`)) {
        stopifnot(is.character(`modelCategory`), length(`modelCategory`) == 1)
      }
      if (!is.null(`projectId`)) {
        stopifnot(is.character(`projectId`), length(`projectId`) == 1)
      }
      if (!is.null(`segmentationTaskId`)) {
        stopifnot(is.character(`segmentationTaskId`), length(`segmentationTaskId`) == 1)
      }
      if (!is.null(`segments`)) {
        stopifnot(is.vector(`segments`), sapply(`segments`, R6::is.R6))
      }
    }
  ),
  public = list(
    `combinedModelId` = NULL,
    `isActiveCombinedModel` = NULL,
    `modelCategory` = NULL,
    `projectId` = NULL,
    `segmentationTaskId` = NULL,
    `segments` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param combinedModelId The ID of combined model.
    #' @param isActiveCombinedModel Indicates whether this model is the active one in segmented modeling project.
    #' @param modelCategory Indicates what kind of model this is. Will be &#x60;&#x60;combined&#x60;&#x60; for combined models.
    #' @param projectId The ID of the project.
    #' @param segmentationTaskId The ID of the segmentation task used to generate this combined model.
    #' @param segments Information for each segment. Maps each segment to the project and model used for it.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`combinedModelId` = NULL, `isActiveCombinedModel` = NULL, `modelCategory` = NULL, `projectId` = NULL, `segmentationTaskId` = NULL, `segments` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`combinedModelId`, `isActiveCombinedModel`, `modelCategory`, `projectId`, `segmentationTaskId`, `segments`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(combinedModelId, isActiveCombinedModel, modelCategory, projectId, segmentationTaskId, segments)
      }
      self$`combinedModelId` <- `combinedModelId`
      self$`isActiveCombinedModel` <- `isActiveCombinedModel`
      self$`modelCategory` <- `modelCategory`
      self$`projectId` <- `projectId`
      self$`segmentationTaskId` <- `segmentationTaskId`
      self$`segments` <- `segments`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(combinedModelId = self$`combinedModelId`, isActiveCombinedModel = self$`isActiveCombinedModel`, modelCategory = self$`modelCategory`, projectId = self$`projectId`, segmentationTaskId = self$`segmentationTaskId`, segments = self$`segments`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`combinedModelId`)) {
          sprintf(
            '"combinedModelId":
            "%s"
                  ',
            self$`combinedModelId`
          )
        },
        if (!is.null(self$`isActiveCombinedModel`)) {
          sprintf(
            '"isActiveCombinedModel":
            %s
                  ',
            tolower(self$`isActiveCombinedModel`)
          )
        },
        if (!is.null(self$`modelCategory`)) {
          sprintf(
            '"modelCategory":
            "%s"
                  ',
            self$`modelCategory`
          )
        },
        if (!is.null(self$`projectId`)) {
          sprintf(
            '"projectId":
            "%s"
                  ',
            self$`projectId`
          )
        },
        if (!is.null(self$`segmentationTaskId`)) {
          sprintf(
            '"segmentationTaskId":
            "%s"
                  ',
            self$`segmentationTaskId`
          )
        },
        if (!is.null(self$`segments`)) {
          sprintf(
            '"segments":
            [%s]
      ',
            paste(sapply(self$`segments`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param CombinedModelResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(CombinedModelResponseJson, validateParams = FALSE) {
      CombinedModelResponseObject <- jsonlite::fromJSON(CombinedModelResponseJson)
      self$`combinedModelId` <- CombinedModelResponseObject$`combinedModelId`
      self$`isActiveCombinedModel` <- CombinedModelResponseObject$`isActiveCombinedModel`
      self$`modelCategory` <- CombinedModelResponseObject$`modelCategory`
      self$`projectId` <- CombinedModelResponseObject$`projectId`
      self$`segmentationTaskId` <- CombinedModelResponseObject$`segmentationTaskId`
      self$`segments` <- ApiClient$new()$deserializeObj(CombinedModelResponseObject$`segments`, "array[SegmentProjectModelResponse]", loadNamespace("datarobot.apicore"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
