# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Comment
#'
#' @description Comment Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field content  character Content of the comment, 10000 symbols max
#'
#' @field entityId  character ID of the entity to post the comment to
#'
#' @field entityType  character Type of the entity to post the comment to, currently only useCase is supported
#'
#' @field mentions  list( character ) [optional] A list of users IDs mentioned in the content
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Comment <- R6::R6Class(
  "Comment",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`content` = NULL, `entityId` = NULL, `entityType` = NULL, `mentions` = NULL) {
      if (!is.null(`content`)) {
        stopifnot(is.character(`content`), length(`content`) == 1)
      }
      if (!is.null(`entityId`)) {
        stopifnot(is.character(`entityId`), length(`entityId`) == 1)
      }
      if (!is.null(`entityType`)) {
        stopifnot(is.character(`entityType`), length(`entityType`) == 1)
      }
      if (!is.null(`mentions`)) {
        stopifnot(is.vector(`mentions`))
      }
    }
  ),
  public = list(
    `content` = NULL,
    `entityId` = NULL,
    `entityType` = NULL,
    `mentions` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param content Content of the comment, 10000 symbols max
    #' @param entityId ID of the entity to post the comment to
    #' @param entityType Type of the entity to post the comment to, currently only useCase is supported
    #' @param mentions A list of users IDs mentioned in the content
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`content` = NULL, `entityId` = NULL, `entityType` = NULL, `mentions` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`content`, `entityId`, `entityType`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(content, entityId, entityType, mentions)
      }
      self$`content` <- `content`
      self$`entityId` <- `entityId`
      self$`entityType` <- `entityType`
      sapply(`mentions`, function(x) stopifnot(is.character(x)))
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(content = self$`content`, entityId = self$`entityId`, entityType = self$`entityType`, mentions = self$`mentions`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`content`)) {
          sprintf(
            '"content":
            "%s"
                  ',
            self$`content`
          )
        },
        if (!is.null(self$`entityId`)) {
          sprintf(
            '"entityId":
            "%s"
                  ',
            self$`entityId`
          )
        },
        if (!is.null(self$`entityType`)) {
          sprintf(
            '"entityType":
            "%s"
                  ',
            self$`entityType`
          )
        },
        if (!is.null(self$`mentions`)) {
          sprintf(
            '"mentions":
            [%s]
                  ',
            paste(unlist(lapply(self$`mentions`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param CommentJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(CommentJson, validateParams = FALSE) {
      CommentObject <- jsonlite::fromJSON(CommentJson)
      self$`content` <- CommentObject$`content`
      self$`entityId` <- CommentObject$`entityId`
      self$`entityType` <- CommentObject$`entityType`
      self$`mentions` <- ApiClient$new()$deserializeObj(CommentObject$`mentions`, "array[character]", loadNamespace("datarobot.apicore"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
