# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ConfusionChartClassMatrix
#'
#' @description ConfusionChartClassMatrix Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field actualCount  integer number of times this class is seen in the validation data
#'
#' @field className  character name of the class
#'
#' @field confusionMatrixOneVsAll  list( \link{array[integer]} ) 2d array representing 2x2 one vs all matrix. This represents the True/False Negative/Positive rates as integer for each class. The data structure looks like: &#x60;&#x60;[ [ True Negative, False Positive ], [ False Negative, True Positive ] ]&#x60;&#x60;
#'
#' @field f1  numeric F1 score
#'
#' @field precision  numeric precision score
#'
#' @field predictedCount  integer number of times this class has been predicted for the validation data
#'
#' @field recall  numeric recall score
#'
#' @field wasActualPercentages  list( \link{ActualPercentages} ) one vs all actual percentages in a format specified below
#'
#' @field wasPredictedPercentages  list( \link{PredictedPercentages} ) one vs all predicted percentages in a format specified below
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ConfusionChartClassMatrix <- R6::R6Class(
  "ConfusionChartClassMatrix",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`actualCount` = NULL, `className` = NULL, `confusionMatrixOneVsAll` = NULL, `f1` = NULL, `precision` = NULL, `predictedCount` = NULL, `recall` = NULL, `wasActualPercentages` = NULL, `wasPredictedPercentages` = NULL) {
      if (!is.null(`actualCount`)) {
        stopifnot(is.numeric(`actualCount`), length(`actualCount`) == 1)
      }
      if (!is.null(`className`)) {
        stopifnot(is.character(`className`), length(`className`) == 1)
      }
      if (!is.null(`confusionMatrixOneVsAll`)) {
        stopifnot(is.vector(`confusionMatrixOneVsAll`))
      }
      if (!is.null(`f1`)) {
      }
      if (!is.null(`precision`)) {
      }
      if (!is.null(`predictedCount`)) {
        stopifnot(is.numeric(`predictedCount`), length(`predictedCount`) == 1)
      }
      if (!is.null(`recall`)) {
      }
      if (!is.null(`wasActualPercentages`)) {
        stopifnot(is.vector(`wasActualPercentages`))
      }
      if (!is.null(`wasPredictedPercentages`)) {
        stopifnot(is.vector(`wasPredictedPercentages`))
      }
    }
  ),
  public = list(
    `actualCount` = NULL,
    `className` = NULL,
    `confusionMatrixOneVsAll` = NULL,
    `f1` = NULL,
    `precision` = NULL,
    `predictedCount` = NULL,
    `recall` = NULL,
    `wasActualPercentages` = NULL,
    `wasPredictedPercentages` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param actualCount number of times this class is seen in the validation data
    #' @param className name of the class
    #' @param confusionMatrixOneVsAll 2d array representing 2x2 one vs all matrix. This represents the True/False Negative/Positive rates as integer for each class. The data structure looks like: &#x60;&#x60;[ [ True Negative, False Positive ], [ False Negative, True Positive ] ]&#x60;&#x60;
    #' @param f1 F1 score
    #' @param precision precision score
    #' @param predictedCount number of times this class has been predicted for the validation data
    #' @param recall recall score
    #' @param wasActualPercentages one vs all actual percentages in a format specified below
    #' @param wasPredictedPercentages one vs all predicted percentages in a format specified below
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`actualCount` = NULL, `className` = NULL, `confusionMatrixOneVsAll` = NULL, `f1` = NULL, `precision` = NULL, `predictedCount` = NULL, `recall` = NULL, `wasActualPercentages` = NULL, `wasPredictedPercentages` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`actualCount`, `className`, `confusionMatrixOneVsAll`, `f1`, `precision`, `predictedCount`, `recall`, `wasActualPercentages`, `wasPredictedPercentages`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(actualCount, className, confusionMatrixOneVsAll, f1, precision, predictedCount, recall, wasActualPercentages, wasPredictedPercentages)
      }
      self$`actualCount` <- `actualCount`
      self$`className` <- `className`
      sapply(`confusionMatrixOneVsAll`, function(x) stopifnot(R6::is.R6(x)))
      self$`f1` <- `f1`
      self$`precision` <- `precision`
      self$`predictedCount` <- `predictedCount`
      self$`recall` <- `recall`
      sapply(`wasActualPercentages`, function(x) stopifnot(R6::is.R6(x)))
      sapply(`wasPredictedPercentages`, function(x) stopifnot(R6::is.R6(x)))
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(actualCount = self$`actualCount`, className = self$`className`, confusionMatrixOneVsAll = self$`confusionMatrixOneVsAll`, f1 = self$`f1`, precision = self$`precision`, predictedCount = self$`predictedCount`, recall = self$`recall`, wasActualPercentages = self$`wasActualPercentages`, wasPredictedPercentages = self$`wasPredictedPercentages`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`actualCount`)) {
          sprintf(
            '"actualCount":
            %d
                  ',
            self$`actualCount`
          )
        },
        if (!is.null(self$`className`)) {
          sprintf(
            '"className":
            "%s"
                  ',
            self$`className`
          )
        },
        if (!is.null(self$`confusionMatrixOneVsAll`)) {
          sprintf(
            '"confusionMatrixOneVsAll":
            [%s]
      ',
            paste(sapply(self$`confusionMatrixOneVsAll`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`f1`)) {
          sprintf(
            '"f1":
            %d
                  ',
            self$`f1`
          )
        },
        if (!is.null(self$`precision`)) {
          sprintf(
            '"precision":
            %d
                  ',
            self$`precision`
          )
        },
        if (!is.null(self$`predictedCount`)) {
          sprintf(
            '"predictedCount":
            %d
                  ',
            self$`predictedCount`
          )
        },
        if (!is.null(self$`recall`)) {
          sprintf(
            '"recall":
            %d
                  ',
            self$`recall`
          )
        },
        if (!is.null(self$`wasActualPercentages`)) {
          sprintf(
            '"wasActualPercentages":
            [%s]
      ',
            paste(sapply(self$`wasActualPercentages`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`wasPredictedPercentages`)) {
          sprintf(
            '"wasPredictedPercentages":
            [%s]
      ',
            paste(sapply(self$`wasPredictedPercentages`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param ConfusionChartClassMatrixJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(ConfusionChartClassMatrixJson, validateParams = FALSE) {
      ConfusionChartClassMatrixObject <- jsonlite::fromJSON(ConfusionChartClassMatrixJson)
      self$`actualCount` <- ConfusionChartClassMatrixObject$`actualCount`
      self$`className` <- ConfusionChartClassMatrixObject$`className`
      self$`confusionMatrixOneVsAll` <- ApiClient$new()$deserializeObj(ConfusionChartClassMatrixObject$`confusionMatrixOneVsAll`, "array[array[integer]]", loadNamespace("datarobot.apicore"))
      self$`f1` <- ConfusionChartClassMatrixObject$`f1`
      self$`precision` <- ConfusionChartClassMatrixObject$`precision`
      self$`predictedCount` <- ConfusionChartClassMatrixObject$`predictedCount`
      self$`recall` <- ConfusionChartClassMatrixObject$`recall`
      self$`wasActualPercentages` <- ApiClient$new()$deserializeObj(ConfusionChartClassMatrixObject$`wasActualPercentages`, "array[ActualPercentages]", loadNamespace("datarobot.apicore"))
      self$`wasPredictedPercentages` <- ApiClient$new()$deserializeObj(ConfusionChartClassMatrixObject$`wasPredictedPercentages`, "array[PredictedPercentages]", loadNamespace("datarobot.apicore"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
