# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CustomModelTests
#'
#' @description CustomModelTests Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field configuration  \link{CustomModelTestsConfig} [optional]
#'
#' @field customModelId  character The ID of the custom model to test.
#'
#' @field customModelVersionId  character The ID of custom model version to use.
#'
#' @field datasetId  character [optional] The ID of the dataset to use for testing. Dataset ID is required for regular (non-unstructured) custom models.
#'
#' @field datasetVersionId  character [optional] The ID of the version of the dataset item to use as the testing dataset. Defaults to the latest version.
#'
#' @field desiredMemory  integer [optional] The amount of memory that is expected to be allocated by the custom model.
#'
#' @field environmentId  character [optional] The ID of environment to use. If not specified, the customModelVersion&#39;s dependency environment will be used.
#'
#' @field environmentVersionId  character [optional] The ID of environment version to use. Defaults to the latest successfully built version.
#'
#' @field maximumMemory  integer [optional] The maximum memory that might be allocated by the custom-model. If exceeded, the custom-model will be killed
#'
#' @field networkEgressPolicy  character [optional] Network egress policy.
#'
#' @field replicas  integer [optional] A fixed number of replicas that will be set for the given custom-model.
#'
#' @field requiresHa  character [optional] Require all custom model replicas to be deployed on different Kubernetes nodes for predictions fault tolerance.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CustomModelTests <- R6::R6Class(
  "CustomModelTests",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(configuration = NULL, customModelId = NULL, customModelVersionId = NULL, datasetId = NULL, datasetVersionId = NULL, desiredMemory = NULL, environmentId = NULL, environmentVersionId = NULL, maximumMemory = NULL, networkEgressPolicy = NULL, replicas = NULL, requiresHa = NULL) {
      if (!is.null(`customModelId`)) {
        stopifnot(is.character(`customModelId`), length(`customModelId`) == 1)
      }
      if (!is.null(`customModelVersionId`)) {
        stopifnot(is.character(`customModelVersionId`), length(`customModelVersionId`) == 1)
      }
      if (!is.null(`configuration`)) {
        stopifnot(R6::is.R6(`configuration`))
      }
      if (!is.null(`datasetId`)) {
        stopifnot(is.character(`datasetId`), length(`datasetId`) == 1)
      }
      if (!is.null(`datasetVersionId`)) {
        stopifnot(is.character(`datasetVersionId`), length(`datasetVersionId`) == 1)
      }
      if (!is.null(`desiredMemory`)) {
        stopifnot(is.numeric(`desiredMemory`), length(`desiredMemory`) == 1)
      }
      if (!is.null(`environmentId`)) {
        stopifnot(is.character(`environmentId`), length(`environmentId`) == 1)
      }
      if (!is.null(`environmentVersionId`)) {
        stopifnot(is.character(`environmentVersionId`), length(`environmentVersionId`) == 1)
      }
      if (!is.null(`maximumMemory`)) {
        stopifnot(is.numeric(`maximumMemory`), length(`maximumMemory`) == 1)
      }
      if (!is.null(`networkEgressPolicy`)) {
        stopifnot(is.character(`networkEgressPolicy`), length(`networkEgressPolicy`) == 1)
      }
      if (!is.null(`replicas`)) {
        stopifnot(is.numeric(`replicas`), length(`replicas`) == 1)
      }
      if (!is.null(`requiresHa`)) {
        stopifnot(is.logical(`requiresHa`), length(`requiresHa`) == 1)
      }
    }
  ),
  public = list(
    `configuration` = NULL,
    `customModelId` = NULL,
    `customModelVersionId` = NULL,
    `datasetId` = NULL,
    `datasetVersionId` = NULL,
    `desiredMemory` = NULL,
    `environmentId` = NULL,
    `environmentVersionId` = NULL,
    `maximumMemory` = NULL,
    `networkEgressPolicy` = NULL,
    `replicas` = NULL,
    `requiresHa` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param configuration
    #' @param customModelId The ID of the custom model to test.
    #' @param customModelVersionId The ID of custom model version to use.
    #' @param datasetId The ID of the dataset to use for testing. Dataset ID is required for regular (non-unstructured) custom models.
    #' @param datasetVersionId The ID of the version of the dataset item to use as the testing dataset. Defaults to the latest version.
    #' @param desiredMemory The amount of memory that is expected to be allocated by the custom model.
    #' @param environmentId The ID of environment to use. If not specified, the customModelVersion&#39;s dependency environment will be used.
    #' @param environmentVersionId The ID of environment version to use. Defaults to the latest successfully built version.
    #' @param maximumMemory The maximum memory that might be allocated by the custom-model. If exceeded, the custom-model will be killed
    #' @param networkEgressPolicy Network egress policy.
    #' @param replicas A fixed number of replicas that will be set for the given custom-model.
    #' @param requiresHa Require all custom model replicas to be deployed on different Kubernetes nodes for predictions fault tolerance.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`customModelId` = NULL, `customModelVersionId` = NULL, `configuration` = NULL, `datasetId` = NULL, `datasetVersionId` = NULL, `desiredMemory` = NULL, `environmentId` = NULL, `environmentVersionId` = NULL, `maximumMemory` = NULL, `networkEgressPolicy` = NULL, `replicas` = NULL, `requiresHa` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`customModelId`, `customModelVersionId`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(configuration, customModelId, customModelVersionId, datasetId, datasetVersionId, desiredMemory, environmentId, environmentVersionId, maximumMemory, networkEgressPolicy, replicas, requiresHa)
      }
      self$`configuration` <- `configuration`
      self$`customModelId` <- `customModelId`
      self$`customModelVersionId` <- `customModelVersionId`
      self$`datasetId` <- `datasetId`
      self$`datasetVersionId` <- `datasetVersionId`
      self$`desiredMemory` <- `desiredMemory`
      self$`environmentId` <- `environmentId`
      self$`environmentVersionId` <- `environmentVersionId`
      self$`maximumMemory` <- `maximumMemory`
      self$`networkEgressPolicy` <- `networkEgressPolicy`
      self$`replicas` <- `replicas`
      self$`requiresHa` <- `requiresHa`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(configuration = self$`configuration`, customModelId = self$`customModelId`, customModelVersionId = self$`customModelVersionId`, datasetId = self$`datasetId`, datasetVersionId = self$`datasetVersionId`, desiredMemory = self$`desiredMemory`, environmentId = self$`environmentId`, environmentVersionId = self$`environmentVersionId`, maximumMemory = self$`maximumMemory`, networkEgressPolicy = self$`networkEgressPolicy`, replicas = self$`replicas`, requiresHa = self$`requiresHa`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`configuration`)) {
          sprintf(
            '"configuration":
          %s
        ',
            jsonlite::toJSON(self$`configuration`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        },
        if (!is.null(self$`customModelId`)) {
          sprintf(
            '"customModelId":
            "%s"
                  ',
            self$`customModelId`
          )
        },
        if (!is.null(self$`customModelVersionId`)) {
          sprintf(
            '"customModelVersionId":
            "%s"
                  ',
            self$`customModelVersionId`
          )
        },
        if (!is.null(self$`datasetId`)) {
          sprintf(
            '"datasetId":
            "%s"
                  ',
            self$`datasetId`
          )
        },
        if (!is.null(self$`datasetVersionId`)) {
          sprintf(
            '"datasetVersionId":
            "%s"
                  ',
            self$`datasetVersionId`
          )
        },
        if (!is.null(self$`desiredMemory`)) {
          sprintf(
            '"desiredMemory":
            %d
                  ',
            self$`desiredMemory`
          )
        },
        if (!is.null(self$`environmentId`)) {
          sprintf(
            '"environmentId":
            "%s"
                  ',
            self$`environmentId`
          )
        },
        if (!is.null(self$`environmentVersionId`)) {
          sprintf(
            '"environmentVersionId":
            "%s"
                  ',
            self$`environmentVersionId`
          )
        },
        if (!is.null(self$`maximumMemory`)) {
          sprintf(
            '"maximumMemory":
            %d
                  ',
            self$`maximumMemory`
          )
        },
        if (!is.null(self$`networkEgressPolicy`)) {
          sprintf(
            '"networkEgressPolicy":
            "%s"
                  ',
            self$`networkEgressPolicy`
          )
        },
        if (!is.null(self$`replicas`)) {
          sprintf(
            '"replicas":
            %d
                  ',
            self$`replicas`
          )
        },
        if (!is.null(self$`requiresHa`)) {
          sprintf(
            '"requiresHa":
            %s
                  ',
            tolower(self$`requiresHa`)
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param CustomModelTestsJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(CustomModelTestsJson, validateParams = FALSE) {
      CustomModelTestsObject <- jsonlite::fromJSON(CustomModelTestsJson)
      self$`configuration` <- CustomModelTestsConfig$new()$fromJSON(jsonlite::toJSON(CustomModelTestsObject$configuration, auto_unbox = TRUE, digits = NA, null = "null"))
      self$`customModelId` <- CustomModelTestsObject$`customModelId`
      self$`customModelVersionId` <- CustomModelTestsObject$`customModelVersionId`
      self$`datasetId` <- CustomModelTestsObject$`datasetId`
      self$`datasetVersionId` <- CustomModelTestsObject$`datasetVersionId`
      self$`desiredMemory` <- CustomModelTestsObject$`desiredMemory`
      self$`environmentId` <- CustomModelTestsObject$`environmentId`
      self$`environmentVersionId` <- CustomModelTestsObject$`environmentVersionId`
      self$`maximumMemory` <- CustomModelTestsObject$`maximumMemory`
      self$`networkEgressPolicy` <- CustomModelTestsObject$`networkEgressPolicy`
      self$`replicas` <- CustomModelTestsObject$`replicas`
      self$`requiresHa` <- CustomModelTestsObject$`requiresHa`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
