# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CustomModelTesting
#'
#' @description CustomModelTesting Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field errorCheck  \link{TestingStatus} [optional]
#'
#' @field longRunningService  \link{TestingStatus} [optional]
#'
#' @field nullValueImputation  \link{TestingStatus} [optional]
#'
#' @field sideEffects  \link{TestingStatus} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CustomModelTesting <- R6::R6Class(
  "CustomModelTesting",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(errorCheck = NULL, longRunningService = NULL, nullValueImputation = NULL, sideEffects = NULL) {
      if (!is.null(`errorCheck`)) {
        stopifnot(R6::is.R6(`errorCheck`))
      }
      if (!is.null(`longRunningService`)) {
        stopifnot(R6::is.R6(`longRunningService`))
      }
      if (!is.null(`nullValueImputation`)) {
        stopifnot(R6::is.R6(`nullValueImputation`))
      }
      if (!is.null(`sideEffects`)) {
        stopifnot(R6::is.R6(`sideEffects`))
      }
    }
  ),
  public = list(
    `errorCheck` = NULL,
    `longRunningService` = NULL,
    `nullValueImputation` = NULL,
    `sideEffects` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param errorCheck
    #' @param longRunningService
    #' @param nullValueImputation
    #' @param sideEffects
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`errorCheck` = NULL, `longRunningService` = NULL, `nullValueImputation` = NULL, `sideEffects` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list()
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(errorCheck, longRunningService, nullValueImputation, sideEffects)
      }
      self$`errorCheck` <- `errorCheck`
      self$`longRunningService` <- `longRunningService`
      self$`nullValueImputation` <- `nullValueImputation`
      self$`sideEffects` <- `sideEffects`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(errorCheck = self$`errorCheck`, longRunningService = self$`longRunningService`, nullValueImputation = self$`nullValueImputation`, sideEffects = self$`sideEffects`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`errorCheck`)) {
          sprintf(
            '"errorCheck":
          %s
        ',
            jsonlite::toJSON(self$`errorCheck`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        },
        if (!is.null(self$`longRunningService`)) {
          sprintf(
            '"longRunningService":
          %s
        ',
            jsonlite::toJSON(self$`longRunningService`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        },
        if (!is.null(self$`nullValueImputation`)) {
          sprintf(
            '"nullValueImputation":
          %s
        ',
            jsonlite::toJSON(self$`nullValueImputation`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        },
        if (!is.null(self$`sideEffects`)) {
          sprintf(
            '"sideEffects":
          %s
        ',
            jsonlite::toJSON(self$`sideEffects`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param CustomModelTestingJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(CustomModelTestingJson, validateParams = FALSE) {
      CustomModelTestingObject <- jsonlite::fromJSON(CustomModelTestingJson)
      self$`errorCheck` <- TestingStatus$new()$fromJSON(jsonlite::toJSON(CustomModelTestingObject$errorCheck, auto_unbox = TRUE, digits = NA, null = "null"))
      self$`longRunningService` <- TestingStatus$new()$fromJSON(jsonlite::toJSON(CustomModelTestingObject$longRunningService, auto_unbox = TRUE, digits = NA, null = "null"))
      self$`nullValueImputation` <- TestingStatus$new()$fromJSON(jsonlite::toJSON(CustomModelTestingObject$nullValueImputation, auto_unbox = TRUE, digits = NA, null = "null"))
      self$`sideEffects` <- TestingStatus$new()$fromJSON(jsonlite::toJSON(CustomModelTestingObject$sideEffects, auto_unbox = TRUE, digits = NA, null = "null"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
