# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CustomTaskResponse
#'
#' @description CustomTaskResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field calibratePredictions  character [optional] Determines whether or not predictions should be calibrated by DataRobot. Only applies to anomaly detection.
#'
#' @field created  character ISO-8601 timestamp of when the task was created.
#'
#' @field createdBy  character The username of the custom task creator.
#'
#' @field customModelType  character The type of custom task.
#'
#' @field description  character The description of the task.
#'
#' @field id  character The ID of the custom task.
#'
#' @field language  character The programming language used by the task.
#'
#' @field latestVersion  \link{CustomTaskVersionResponse}
#'
#' @field maximumMemory  integer [optional] The maximum memory that might be allocated by the custom-model. If exceeded, the custom-model will be killed
#'
#' @field name  character The name of the task.
#'
#' @field targetType  character The target type of the custom task.
#'
#' @field updated  character ISO-8601 timestamp of when task was last updated.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CustomTaskResponse <- R6::R6Class(
  "CustomTaskResponse",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`calibratePredictions` = NULL, `created` = NULL, `createdBy` = NULL, `customModelType` = NULL, `description` = NULL, `id` = NULL, `language` = NULL, `latestVersion` = NULL, `maximumMemory` = NULL, `name` = NULL, `targetType` = NULL, `updated` = NULL) {
      if (!is.null(`created`)) {
        stopifnot(is.character(`created`), length(`created`) == 1)
      }
      if (!is.null(`createdBy`)) {
        stopifnot(is.character(`createdBy`), length(`createdBy`) == 1)
      }
      if (!is.null(`customModelType`)) {
        stopifnot(is.character(`customModelType`), length(`customModelType`) == 1)
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
      }
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
      }
      if (!is.null(`language`)) {
        stopifnot(is.character(`language`), length(`language`) == 1)
      }
      if (!is.null(`latestVersion`)) {
        stopifnot(R6::is.R6(`latestVersion`))
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
      }
      if (!is.null(`targetType`)) {
        stopifnot(is.character(`targetType`), length(`targetType`) == 1)
      }
      if (!is.null(`updated`)) {
        stopifnot(is.character(`updated`), length(`updated`) == 1)
      }
      if (!is.null(`calibratePredictions`)) {
        stopifnot(is.logical(`calibratePredictions`), length(`calibratePredictions`) == 1)
      }
      if (!is.null(`maximumMemory`)) {
        stopifnot(is.numeric(`maximumMemory`), length(`maximumMemory`) == 1)
      }
    }
  ),
  public = list(
    `calibratePredictions` = NULL,
    `created` = NULL,
    `createdBy` = NULL,
    `customModelType` = NULL,
    `description` = NULL,
    `id` = NULL,
    `language` = NULL,
    `latestVersion` = NULL,
    `maximumMemory` = NULL,
    `name` = NULL,
    `targetType` = NULL,
    `updated` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param calibratePredictions Determines whether or not predictions should be calibrated by DataRobot. Only applies to anomaly detection.
    #' @param created ISO-8601 timestamp of when the task was created.
    #' @param createdBy The username of the custom task creator.
    #' @param customModelType The type of custom task.
    #' @param description The description of the task.
    #' @param id The ID of the custom task.
    #' @param language The programming language used by the task.
    #' @param latestVersion
    #' @param maximumMemory The maximum memory that might be allocated by the custom-model. If exceeded, the custom-model will be killed
    #' @param name The name of the task.
    #' @param targetType The target type of the custom task.
    #' @param updated ISO-8601 timestamp of when task was last updated.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`created` = NULL, `createdBy` = NULL, `customModelType` = NULL, `description` = NULL, `id` = NULL, `language` = NULL, `latestVersion` = NULL, `name` = NULL, `targetType` = NULL, `updated` = NULL, `calibratePredictions` = NULL, `maximumMemory` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`created`, `createdBy`, `customModelType`, `description`, `id`, `language`, `latestVersion`, `name`, `targetType`, `updated`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(calibratePredictions, created, createdBy, customModelType, description, id, language, latestVersion, maximumMemory, name, targetType, updated)
      }
      self$`calibratePredictions` <- `calibratePredictions`
      self$`created` <- `created`
      self$`createdBy` <- `createdBy`
      self$`customModelType` <- `customModelType`
      self$`description` <- `description`
      self$`id` <- `id`
      self$`language` <- `language`
      self$`latestVersion` <- `latestVersion`
      self$`maximumMemory` <- `maximumMemory`
      self$`name` <- `name`
      self$`targetType` <- `targetType`
      self$`updated` <- `updated`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(calibratePredictions = self$`calibratePredictions`, created = self$`created`, createdBy = self$`createdBy`, customModelType = self$`customModelType`, description = self$`description`, id = self$`id`, language = self$`language`, latestVersion = self$`latestVersion`, maximumMemory = self$`maximumMemory`, name = self$`name`, targetType = self$`targetType`, updated = self$`updated`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`calibratePredictions`)) {
          sprintf(
            '"calibratePredictions":
            %s
                  ',
            tolower(self$`calibratePredictions`)
          )
        },
        if (!is.null(self$`created`)) {
          sprintf(
            '"created":
            "%s"
                  ',
            self$`created`
          )
        },
        if (!is.null(self$`createdBy`)) {
          sprintf(
            '"createdBy":
            "%s"
                  ',
            self$`createdBy`
          )
        },
        if (!is.null(self$`customModelType`)) {
          sprintf(
            '"customModelType":
            "%s"
                  ',
            self$`customModelType`
          )
        },
        if (!is.null(self$`description`)) {
          sprintf(
            '"description":
            "%s"
                  ',
            self$`description`
          )
        },
        if (!is.null(self$`id`)) {
          sprintf(
            '"id":
            "%s"
                  ',
            self$`id`
          )
        },
        if (!is.null(self$`language`)) {
          sprintf(
            '"language":
            "%s"
                  ',
            self$`language`
          )
        },
        if (!is.null(self$`latestVersion`)) {
          sprintf(
            '"latestVersion":
            %s
      ',
            jsonlite::toJSON(self$`latestVersion`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        },
        if (!is.null(self$`maximumMemory`)) {
          sprintf(
            '"maximumMemory":
            %d
                  ',
            self$`maximumMemory`
          )
        },
        if (!is.null(self$`name`)) {
          sprintf(
            '"name":
            "%s"
                  ',
            self$`name`
          )
        },
        if (!is.null(self$`targetType`)) {
          sprintf(
            '"targetType":
            "%s"
                  ',
            self$`targetType`
          )
        },
        if (!is.null(self$`updated`)) {
          sprintf(
            '"updated":
            "%s"
                  ',
            self$`updated`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param CustomTaskResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(CustomTaskResponseJson, validateParams = FALSE) {
      CustomTaskResponseObject <- jsonlite::fromJSON(CustomTaskResponseJson)
      self$`calibratePredictions` <- CustomTaskResponseObject$`calibratePredictions`
      self$`created` <- CustomTaskResponseObject$`created`
      self$`createdBy` <- CustomTaskResponseObject$`createdBy`
      self$`customModelType` <- CustomTaskResponseObject$`customModelType`
      self$`description` <- CustomTaskResponseObject$`description`
      self$`id` <- CustomTaskResponseObject$`id`
      self$`language` <- CustomTaskResponseObject$`language`
      self$`latestVersion` <- CustomTaskVersionResponse$new()$fromJSON(jsonlite::toJSON(CustomTaskResponseObject$latestVersion, auto_unbox = TRUE, digits = NA, null = "null"))
      self$`maximumMemory` <- CustomTaskResponseObject$`maximumMemory`
      self$`name` <- CustomTaskResponseObject$`name`
      self$`targetType` <- CustomTaskResponseObject$`targetType`
      self$`updated` <- CustomTaskResponseObject$`updated`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
