# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CustomModelConversionAsyncOperationResponse
#'
#' @description CustomModelConversionAsyncOperationResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field conversionId  character ID that can be used to stop a given conversion.
#'
#' @field statusId  character ID that can be used with :http:get:&#x60;/api/v2/status/(statusId)/&#x60; to poll for the testing job&#39;s status
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CustomModelConversionAsyncOperationResponse <- R6::R6Class(
  "CustomModelConversionAsyncOperationResponse",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(conversionId = NULL, statusId = NULL) {
      if (!is.null(`conversionId`)) {
        stopifnot(is.character(`conversionId`), length(`conversionId`) == 1)
      }
      if (!is.null(`statusId`)) {
        stopifnot(is.character(`statusId`), length(`statusId`) == 1)
      }
    }
  ),
  public = list(
    `conversionId` = NULL,
    `statusId` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param conversionId ID that can be used to stop a given conversion.
    #' @param statusId ID that can be used with :http:get:&#x60;/api/v2/status/(statusId)/&#x60; to poll for the testing job&#39;s status
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`conversionId` = NULL, `statusId` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`conversionId`, `statusId`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(conversionId, statusId)
      }
      self$`conversionId` <- `conversionId`
      self$`statusId` <- `statusId`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(conversionId = self$`conversionId`, statusId = self$`statusId`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`conversionId`)) {
          sprintf(
            '"conversionId":
            "%s"
                  ',
            self$`conversionId`
          )
        },
        if (!is.null(self$`statusId`)) {
          sprintf(
            '"statusId":
            "%s"
                  ',
            self$`statusId`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param CustomModelConversionAsyncOperationResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(CustomModelConversionAsyncOperationResponseJson, validateParams = FALSE) {
      CustomModelConversionAsyncOperationResponseObject <- jsonlite::fromJSON(CustomModelConversionAsyncOperationResponseJson)
      self$`conversionId` <- CustomModelConversionAsyncOperationResponseObject$`conversionId`
      self$`statusId` <- CustomModelConversionAsyncOperationResponseObject$`statusId`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
