# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DataSourceUpdate
#'
#' @description DataSourceUpdate Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field canonicalName  character [optional] Data source canonical name.
#'
#' @field params  \link{OneOfOptionalJDBCTableDataSourceOptionalJDBCQueryDataSourceOptionalDRConnectorV1DataSource} [optional] Data source configuration.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DataSourceUpdate <- R6::R6Class(
  "DataSourceUpdate",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(canonicalName = NULL, params = NULL) {
      if (!is.null(`canonicalName`)) {
        stopifnot(is.character(`canonicalName`), length(`canonicalName`) == 1)
      }
      if (!is.null(`params`)) {
        .setComplexProperty(typeList = list(OptionalJDBCTableDataSource, OptionalJDBCQueryDataSource, OptionalDRConnectorV1DataSource), propertyData = params)
      }
    }
  ),
  public = list(
    `canonicalName` = NULL,
    `params` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param canonicalName Data source canonical name.
    #' @param params Data source configuration.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`canonicalName` = NULL, `params` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list()
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(canonicalName, params)
      }
      self$`canonicalName` <- `canonicalName`
      self$`params` <- .setComplexProperty(typeList = list(OptionalJDBCTableDataSource, OptionalJDBCQueryDataSource, OptionalDRConnectorV1DataSource), propertyData = params)
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(canonicalName = self$`canonicalName`, params = self$`params`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`canonicalName`)) {
          sprintf(
            '"canonicalName":
            "%s"
                  ',
            self$`canonicalName`
          )
        },
        if (!is.null(self$`params`)) {
          sprintf(
            '"params":
          %s
        ',
            jsonlite::toJSON(self$`params`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param DataSourceUpdateJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(DataSourceUpdateJson, validateParams = FALSE) {
      DataSourceUpdateObject <- jsonlite::fromJSON(DataSourceUpdateJson)
      self$`canonicalName` <- DataSourceUpdateObject$`canonicalName`
      self$`params` <- .setComplexProperty(typeList = list(OptionalJDBCTableDataSource, OptionalJDBCQueryDataSource, OptionalDRConnectorV1DataSource), propertyData = DataSourceUpdateObject$params)

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
