# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DataStoreSchemasList
#'
#' @description DataStoreSchemasList Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field catalog  character Name of the catalog associated with the schemas. If more than one catalog is queried, the returned value will be the catalog name for the first record returned.
#'
#' @field catalogs  list( character ) List of catalogs associated with each retrieved schema. If no catalog is found, this value is null.
#'
#' @field schemas  list( character ) List of schemas available in the data store.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DataStoreSchemasList <- R6::R6Class(
  "DataStoreSchemasList",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`catalog` = NULL, `catalogs` = NULL, `schemas` = NULL) {
      if (!is.null(`catalog`)) {
        stopifnot(is.character(`catalog`), length(`catalog`) == 1)
      }
      if (!is.null(`catalogs`)) {
        stopifnot(is.vector(`catalogs`))
      }
      if (!is.null(`schemas`)) {
        stopifnot(is.vector(`schemas`))
      }
    }
  ),
  public = list(
    `catalog` = NULL,
    `catalogs` = NULL,
    `schemas` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param catalog Name of the catalog associated with the schemas. If more than one catalog is queried, the returned value will be the catalog name for the first record returned.
    #' @param catalogs List of catalogs associated with each retrieved schema. If no catalog is found, this value is null.
    #' @param schemas List of schemas available in the data store.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`catalog` = NULL, `catalogs` = NULL, `schemas` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`catalog`, `catalogs`, `schemas`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(catalog, catalogs, schemas)
      }
      self$`catalog` <- `catalog`
      sapply(`catalogs`, function(x) stopifnot(is.character(x)))
      sapply(`schemas`, function(x) stopifnot(is.character(x)))
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(catalog = self$`catalog`, catalogs = self$`catalogs`, schemas = self$`schemas`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`catalog`)) {
          sprintf(
            '"catalog":
            "%s"
                  ',
            self$`catalog`
          )
        },
        if (!is.null(self$`catalogs`)) {
          sprintf(
            '"catalogs":
            [%s]
                  ',
            paste(unlist(lapply(self$`catalogs`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`schemas`)) {
          sprintf(
            '"schemas":
            [%s]
                  ',
            paste(unlist(lapply(self$`schemas`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param DataStoreSchemasListJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(DataStoreSchemasListJson, validateParams = FALSE) {
      DataStoreSchemasListObject <- jsonlite::fromJSON(DataStoreSchemasListJson)
      self$`catalog` <- DataStoreSchemasListObject$`catalog`
      self$`catalogs` <- ApiClient$new()$deserializeObj(DataStoreSchemasListObject$`catalogs`, "array[character]", loadNamespace("datarobot.apicore"))
      self$`schemas` <- ApiClient$new()$deserializeObj(DataStoreSchemasListObject$`schemas`, "array[character]", loadNamespace("datarobot.apicore"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
