# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DataStoreColumnsListResponse
#'
#' @description DataStoreColumnsListResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field columns  list( \link{DataStoreColumnResponse} ) List of data store columns.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DataStoreColumnsListResponse <- R6::R6Class(
  "DataStoreColumnsListResponse",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`columns` = NULL) {
      if (!is.null(`columns`)) {
        stopifnot(is.vector(`columns`))
      }
    }
  ),
  public = list(
    `columns` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param columns List of data store columns.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`columns` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`columns`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(columns)
      }
      sapply(`columns`, function(x) stopifnot(R6::is.R6(x)))
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(columns = self$`columns`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`columns`)) {
          sprintf(
            '"columns":
            [%s]
      ',
            paste(sapply(self$`columns`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param DataStoreColumnsListResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(DataStoreColumnsListResponseJson, validateParams = FALSE) {
      DataStoreColumnsListResponseObject <- jsonlite::fromJSON(DataStoreColumnsListResponseJson)
      self$`columns` <- ApiClient$new()$deserializeObj(DataStoreColumnsListResponseObject$`columns`, "array[DataStoreColumnResponse]", loadNamespace("datarobot.apicore"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
