# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DerivedFeatures
#'
#' @description DerivedFeatures Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field coefficient  numeric The coefficient for this feature.
#'
#' @field derivedFeature  character The name of the derived feature.
#'
#' @field originalFeature  character The name of the feature used to derive this feature.
#'
#' @field stageCoefficients  list( \link{StageCoefficients} ) An array of json objects describing separate coefficients for every stage of model (empty for single stage models).
#'
#' @field transformations  list( \link{Transformations} ) An array of json objects describing the transformations applied to create this derived feature.
#'
#' @field type  character The type of this feature.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DerivedFeatures <- R6::R6Class(
  "DerivedFeatures",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`coefficient` = NULL, `derivedFeature` = NULL, `originalFeature` = NULL, `stageCoefficients` = NULL, `transformations` = NULL, `type` = NULL) {
      if (!is.null(`coefficient`)) {
      }
      if (!is.null(`derivedFeature`)) {
        stopifnot(is.character(`derivedFeature`), length(`derivedFeature`) == 1)
      }
      if (!is.null(`originalFeature`)) {
        stopifnot(is.character(`originalFeature`), length(`originalFeature`) == 1)
      }
      if (!is.null(`stageCoefficients`)) {
        stopifnot(is.vector(`stageCoefficients`))
      }
      if (!is.null(`transformations`)) {
        stopifnot(is.vector(`transformations`))
      }
      if (!is.null(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
      }
    }
  ),
  public = list(
    `coefficient` = NULL,
    `derivedFeature` = NULL,
    `originalFeature` = NULL,
    `stageCoefficients` = NULL,
    `transformations` = NULL,
    `type` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param coefficient The coefficient for this feature.
    #' @param derivedFeature The name of the derived feature.
    #' @param originalFeature The name of the feature used to derive this feature.
    #' @param stageCoefficients An array of json objects describing separate coefficients for every stage of model (empty for single stage models).
    #' @param transformations An array of json objects describing the transformations applied to create this derived feature.
    #' @param type The type of this feature.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`coefficient` = NULL, `derivedFeature` = NULL, `originalFeature` = NULL, `stageCoefficients` = NULL, `transformations` = NULL, `type` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`coefficient`, `derivedFeature`, `originalFeature`, `stageCoefficients`, `transformations`, `type`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(coefficient, derivedFeature, originalFeature, stageCoefficients, transformations, type)
      }
      self$`coefficient` <- `coefficient`
      self$`derivedFeature` <- `derivedFeature`
      self$`originalFeature` <- `originalFeature`
      sapply(`stageCoefficients`, function(x) stopifnot(R6::is.R6(x)))
      sapply(`transformations`, function(x) stopifnot(R6::is.R6(x)))
      self$`type` <- `type`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(coefficient = self$`coefficient`, derivedFeature = self$`derivedFeature`, originalFeature = self$`originalFeature`, stageCoefficients = self$`stageCoefficients`, transformations = self$`transformations`, type = self$`type`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`coefficient`)) {
          sprintf(
            '"coefficient":
            %d
                  ',
            self$`coefficient`
          )
        },
        if (!is.null(self$`derivedFeature`)) {
          sprintf(
            '"derivedFeature":
            "%s"
                  ',
            self$`derivedFeature`
          )
        },
        if (!is.null(self$`originalFeature`)) {
          sprintf(
            '"originalFeature":
            "%s"
                  ',
            self$`originalFeature`
          )
        },
        if (!is.null(self$`stageCoefficients`)) {
          sprintf(
            '"stageCoefficients":
            [%s]
      ',
            paste(sapply(self$`stageCoefficients`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`transformations`)) {
          sprintf(
            '"transformations":
            [%s]
      ',
            paste(sapply(self$`transformations`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`type`)) {
          sprintf(
            '"type":
            "%s"
                  ',
            self$`type`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param DerivedFeaturesJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(DerivedFeaturesJson, validateParams = FALSE) {
      DerivedFeaturesObject <- jsonlite::fromJSON(DerivedFeaturesJson)
      self$`coefficient` <- DerivedFeaturesObject$`coefficient`
      self$`derivedFeature` <- DerivedFeaturesObject$`derivedFeature`
      self$`originalFeature` <- DerivedFeaturesObject$`originalFeature`
      self$`stageCoefficients` <- ApiClient$new()$deserializeObj(DerivedFeaturesObject$`stageCoefficients`, "array[StageCoefficients]", loadNamespace("datarobot.apicore"))
      self$`transformations` <- ApiClient$new()$deserializeObj(DerivedFeaturesObject$`transformations`, "array[Transformations]", loadNamespace("datarobot.apicore"))
      self$`type` <- DerivedFeaturesObject$`type`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
