# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title EmbeddingsRetrieveResponse
#'
#' @description EmbeddingsRetrieveResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field embeddings  list( \link{ImageEmbedding} ) List of Image Embedding objects
#'
#' @field targetBins  list( \link{TargetBin} ) List of bin objects for regression or null
#'
#' @field targetValues  list( character ) List of target values for classification or null
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EmbeddingsRetrieveResponse <- R6::R6Class(
  "EmbeddingsRetrieveResponse",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`embeddings` = NULL, `targetBins` = NULL, `targetValues` = NULL) {
      if (!is.null(`embeddings`)) {
        stopifnot(is.vector(`embeddings`), sapply(`embeddings`, R6::is.R6))
      }
      if (!is.null(`targetBins`)) {
        stopifnot(is.vector(`targetBins`), sapply(`targetBins`, R6::is.R6))
      }
      if (!is.null(`targetValues`)) {
        stopifnot(is.vector(`targetValues`), sapply(`targetValues`, is.character))
      }
    }
  ),
  public = list(
    `embeddings` = NULL,
    `targetBins` = NULL,
    `targetValues` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param embeddings List of Image Embedding objects
    #' @param targetBins List of bin objects for regression or null
    #' @param targetValues List of target values for classification or null
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`embeddings` = NULL, `targetBins` = NULL, `targetValues` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`embeddings`, `targetBins`, `targetValues`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(embeddings, targetBins, targetValues)
      }
      self$`embeddings` <- `embeddings`
      self$`targetBins` <- `targetBins`
      self$`targetValues` <- `targetValues`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(embeddings = self$`embeddings`, targetBins = self$`targetBins`, targetValues = self$`targetValues`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`embeddings`)) {
          sprintf(
            '"embeddings":
            [%s]
      ',
            paste(sapply(self$`embeddings`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`targetBins`)) {
          sprintf(
            '"targetBins":
            [%s]
      ',
            paste(sapply(self$`targetBins`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`targetValues`)) {
          sprintf(
            '"targetValues":
            [%s]
                  ',
            paste(unlist(lapply(self$`targetValues`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param EmbeddingsRetrieveResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(EmbeddingsRetrieveResponseJson, validateParams = FALSE) {
      EmbeddingsRetrieveResponseObject <- jsonlite::fromJSON(EmbeddingsRetrieveResponseJson)
      self$`embeddings` <- ApiClient$new()$deserializeObj(EmbeddingsRetrieveResponseObject$`embeddings`, "array[ImageEmbedding]", loadNamespace("datarobot.apicore"))
      self$`targetBins` <- ApiClient$new()$deserializeObj(EmbeddingsRetrieveResponseObject$`targetBins`, "array[TargetBin]", loadNamespace("datarobot.apicore"))
      self$`targetValues` <- ApiClient$new()$deserializeObj(EmbeddingsRetrieveResponseObject$`targetValues`, "array[character]", loadNamespace("datarobot.apicore"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
