# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ExternalTSBaselineMetadata
#'
#' @description ExternalTSBaselineMetadata Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field datasetId  character Catalog version id for external prediction data that can be used as a baseline to calculate new metrics.
#'
#' @field datasetName  character The name of the timeseries baseline dataset for the project
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ExternalTSBaselineMetadata <- R6::R6Class(
  "ExternalTSBaselineMetadata",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(datasetId = NULL, datasetName = NULL) {
      if (!is.null(`datasetId`)) {
        stopifnot(is.character(`datasetId`), length(`datasetId`) == 1)
      }
      if (!is.null(`datasetName`)) {
        stopifnot(is.character(`datasetName`), length(`datasetName`) == 1)
      }
    }
  ),
  public = list(
    `datasetId` = NULL,
    `datasetName` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param datasetId Catalog version id for external prediction data that can be used as a baseline to calculate new metrics.
    #' @param datasetName The name of the timeseries baseline dataset for the project
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`datasetId` = NULL, `datasetName` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`datasetId`, `datasetName`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(datasetId, datasetName)
      }
      self$`datasetId` <- `datasetId`
      self$`datasetName` <- `datasetName`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(datasetId = self$`datasetId`, datasetName = self$`datasetName`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`datasetId`)) {
          sprintf(
            '"datasetId":
            "%s"
                  ',
            self$`datasetId`
          )
        },
        if (!is.null(self$`datasetName`)) {
          sprintf(
            '"datasetName":
            "%s"
                  ',
            self$`datasetName`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param ExternalTSBaselineMetadataJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(ExternalTSBaselineMetadataJson, validateParams = FALSE) {
      ExternalTSBaselineMetadataObject <- jsonlite::fromJSON(ExternalTSBaselineMetadataJson)
      self$`datasetId` <- ExternalTSBaselineMetadataObject$`datasetId`
      self$`datasetName` <- ExternalTSBaselineMetadataObject$`datasetName`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
