# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FeatureAssociationRetrieveControllerResponse
#'
#' @description FeatureAssociationRetrieveControllerResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field features  list( \link{FeatureAssociationRetrieveFeatures} ) Metadata for each feature and where it goes in the matrix as structured below.
#'
#' @field strengths  list( \link{FeatureAssociationRetrieveStrengths} ) Pairwise statistics for the available features as structured below.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FeatureAssociationRetrieveControllerResponse <- R6::R6Class(
  "FeatureAssociationRetrieveControllerResponse",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(features = NULL, strengths = NULL) {
      if (!is.null(`features`)) {
        stopifnot(is.vector(`features`))
      }
      if (!is.null(`strengths`)) {
        stopifnot(is.vector(`strengths`))
      }
    }
  ),
  public = list(
    `features` = NULL,
    `strengths` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param features Metadata for each feature and where it goes in the matrix as structured below.
    #' @param strengths Pairwise statistics for the available features as structured below.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`features` = NULL, `strengths` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`features`, `strengths`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(features, strengths)
      }
      sapply(`features`, function(x) stopifnot(R6::is.R6(x)))
      sapply(`strengths`, function(x) stopifnot(R6::is.R6(x)))
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(features = self$`features`, strengths = self$`strengths`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`features`)) {
          sprintf(
            '"features":
            [%s]
',
            paste(sapply(self$`features`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`strengths`)) {
          sprintf(
            '"strengths":
            [%s]
',
            paste(sapply(self$`strengths`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param FeatureAssociationRetrieveControllerResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(FeatureAssociationRetrieveControllerResponseJson, validateParams = FALSE) {
      FeatureAssociationRetrieveControllerResponseObject <- jsonlite::fromJSON(FeatureAssociationRetrieveControllerResponseJson)
      self$`features` <- ApiClient$new()$deserializeObj(FeatureAssociationRetrieveControllerResponseObject$`features`, "array[FeatureAssociationRetrieveFeatures]", loadNamespace("datarobot.apicore"))
      self$`strengths` <- ApiClient$new()$deserializeObj(FeatureAssociationRetrieveControllerResponseObject$`strengths`, "array[FeatureAssociationRetrieveStrengths]", loadNamespace("datarobot.apicore"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
