# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FeatureDiscoveryLogListResponse
#'
#' @description FeatureDiscoveryLogListResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field count  integer Number of items returned on this page
#'
#' @field featureDiscoveryLog  list( character ) List of lines retrieved from the feature discovery log
#'
#' @field next_  character URL pointing to the next page (if null, there is no next page)
#'
#' @field previous  character URL pointing to the previous page (if null, there is no previous page)
#'
#' @field totalLogLines  integer total number of lines in feature derivation log
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FeatureDiscoveryLogListResponse <- R6::R6Class(
  "FeatureDiscoveryLogListResponse",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(count = NULL, featureDiscoveryLog = NULL, next_ = NULL, previous = NULL, totalLogLines = NULL) {
      if (!is.null(`count`)) {
        stopifnot(is.numeric(`count`), length(`count`) == 1)
      }
      if (!is.null(`featureDiscoveryLog`)) {
        stopifnot(is.vector(`featureDiscoveryLog`))
      }
      if (!is.null(`next_`)) {
        stopifnot(is.character(`next_`), length(`next_`) == 1)
      }
      if (!is.null(`previous`)) {
        stopifnot(is.character(`previous`), length(`previous`) == 1)
      }
      if (!is.null(`totalLogLines`)) {
        stopifnot(is.numeric(`totalLogLines`), length(`totalLogLines`) == 1)
      }
    }
  ),
  public = list(
    `count` = NULL,
    `featureDiscoveryLog` = NULL,
    `next_` = NULL,
    `previous` = NULL,
    `totalLogLines` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param count Number of items returned on this page
    #' @param featureDiscoveryLog List of lines retrieved from the feature discovery log
    #' @param next_ URL pointing to the next page (if null, there is no next page)
    #' @param previous URL pointing to the previous page (if null, there is no previous page)
    #' @param totalLogLines total number of lines in feature derivation log
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`count` = NULL, `featureDiscoveryLog` = NULL, `next_` = NULL, `previous` = NULL, `totalLogLines` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`count`, `featureDiscoveryLog`, `next_`, `previous`, `totalLogLines`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(count, featureDiscoveryLog, next_, previous, totalLogLines)
      }
      self$`count` <- `count`
      sapply(`featureDiscoveryLog`, function(x) stopifnot(is.character(x)))
      self$`next_` <- `next_`
      self$`previous` <- `previous`
      self$`totalLogLines` <- `totalLogLines`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(count = self$`count`, featureDiscoveryLog = self$`featureDiscoveryLog`, next_ = self$`next_`, previous = self$`previous`, totalLogLines = self$`totalLogLines`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`count`)) {
          sprintf(
            '"count":
            %d
                  ',
            self$`count`
          )
        },
        if (!is.null(self$`featureDiscoveryLog`)) {
          sprintf(
            '"featureDiscoveryLog":
              [%s]
            ',
            paste(unlist(lapply(self$`featureDiscoveryLog`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`next_`)) {
          sprintf(
            '"next":
            "%s"
                  ',
            self$`next_`
          )
        },
        if (!is.null(self$`previous`)) {
          sprintf(
            '"previous":
            "%s"
                  ',
            self$`previous`
          )
        },
        if (!is.null(self$`totalLogLines`)) {
          sprintf(
            '"totalLogLines":
            %d
                  ',
            self$`totalLogLines`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param FeatureDiscoveryLogListResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(FeatureDiscoveryLogListResponseJson, validateParams = FALSE) {
      FeatureDiscoveryLogListResponseObject <- jsonlite::fromJSON(FeatureDiscoveryLogListResponseJson)
      self$`count` <- FeatureDiscoveryLogListResponseObject$`count`
      self$`featureDiscoveryLog` <- ApiClient$new()$deserializeObj(FeatureDiscoveryLogListResponseObject$`featureDiscoveryLog`, "array[character]", loadNamespace("datarobot.apicore"))
      self$`next_` <- FeatureDiscoveryLogListResponseObject$`next`
      self$`previous` <- FeatureDiscoveryLogListResponseObject$`previous`
      self$`totalLogLines` <- FeatureDiscoveryLogListResponseObject$`totalLogLines`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
