# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FeatureEffectsDatetimeResponse
#'
#' @description FeatureEffectsDatetimeResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field backtestIndex  character The backtest index. For example: &#x60;0&#x60;, &#x60;1&#x60;, ..., &#x60;20&#x60;, &#x60;holdout&#x60;, &#x60;startstop&#x60;.
#'
#' @field featureEffects  list( \link{FeatureEffects} ) Feature Effects computational results for each feature.
#'
#' @field modelId  character The model ID
#'
#' @field projectId  character The project ID
#'
#' @field source  character Models data source.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FeatureEffectsDatetimeResponse <- R6::R6Class(
  "FeatureEffectsDatetimeResponse",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(backtestIndex = NULL, featureEffects = NULL, modelId = NULL, projectId = NULL, source = NULL) {
      if (!is.null(`backtestIndex`)) {
        stopifnot(is.character(`backtestIndex`), length(`backtestIndex`) == 1)
      }
      if (!is.null(`featureEffects`)) {
        stopifnot(is.vector(`featureEffects`))
      }
      if (!is.null(`modelId`)) {
        stopifnot(is.character(`modelId`), length(`modelId`) == 1)
      }
      if (!is.null(`projectId`)) {
        stopifnot(is.character(`projectId`), length(`projectId`) == 1)
      }
      if (!is.null(`source`)) {
        stopifnot(is.character(`source`), length(`source`) == 1)
      }
    }
  ),
  public = list(
    `backtestIndex` = NULL,
    `featureEffects` = NULL,
    `modelId` = NULL,
    `projectId` = NULL,
    `source` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param backtestIndex The backtest index. For example: &#x60;0&#x60;, &#x60;1&#x60;, ..., &#x60;20&#x60;, &#x60;holdout&#x60;, &#x60;startstop&#x60;.
    #' @param featureEffects Feature Effects computational results for each feature.
    #' @param modelId The model ID
    #' @param projectId The project ID
    #' @param source Models data source.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`backtestIndex` = NULL, `featureEffects` = NULL, `modelId` = NULL, `projectId` = NULL, `source` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`backtestIndex`, `featureEffects`, `modelId`, `projectId`, `source`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(backtestIndex, featureEffects, modelId, projectId, source)
      }
      self$`backtestIndex` <- `backtestIndex`
      sapply(`featureEffects`, function(x) stopifnot(R6::is.R6(x)))
      self$`modelId` <- `modelId`
      self$`projectId` <- `projectId`
      self$`source` <- `source`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(backtestIndex = self$`backtestIndex`, featureEffects = self$`featureEffects`, modelId = self$`modelId`, projectId = self$`projectId`, source = self$`source`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`backtestIndex`)) {
          sprintf(
            '"backtestIndex":
            "%s"
                  ',
            self$`backtestIndex`
          )
        },
        if (!is.null(self$`featureEffects`)) {
          sprintf(
            '"featureEffects":
            [%s]
',
            paste(sapply(self$`featureEffects`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`modelId`)) {
          sprintf(
            '"modelId":
            "%s"
                  ',
            self$`modelId`
          )
        },
        if (!is.null(self$`projectId`)) {
          sprintf(
            '"projectId":
            "%s"
                  ',
            self$`projectId`
          )
        },
        if (!is.null(self$`source`)) {
          sprintf(
            '"source":
            "%s"
                  ',
            self$`source`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param FeatureEffectsDatetimeResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(FeatureEffectsDatetimeResponseJson, validateParams = FALSE) {
      FeatureEffectsDatetimeResponseObject <- jsonlite::fromJSON(FeatureEffectsDatetimeResponseJson)
      self$`backtestIndex` <- FeatureEffectsDatetimeResponseObject$`backtestIndex`
      self$`featureEffects` <- ApiClient$new()$deserializeObj(FeatureEffectsDatetimeResponseObject$`featureEffects`, "array[FeatureEffects]", loadNamespace("datarobot.apicore"))
      self$`modelId` <- FeatureEffectsDatetimeResponseObject$`modelId`
      self$`projectId` <- FeatureEffectsDatetimeResponseObject$`projectId`
      self$`source` <- FeatureEffectsDatetimeResponseObject$`source`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
