# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FeatureEffectCreate
#'
#' @description FeatureEffectCreate Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field rowCount  integer [optional] The number of rows from dataset to use for Feature Impact calculation.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FeatureEffectCreate <- R6::R6Class(
  "FeatureEffectCreate",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(rowCount = NULL) {
      if (!is.null(`rowCount`)) {
        stopifnot(is.numeric(`rowCount`), length(`rowCount`) == 1)
      }
    }
  ),
  public = list(
    `rowCount` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param rowCount The number of rows from dataset to use for Feature Impact calculation.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`rowCount` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list()
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(rowCount)
      }
      self$`rowCount` <- `rowCount`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(rowCount = self$`rowCount`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`rowCount`)) {
          sprintf(
            '"rowCount":
            %d
                  ',
            self$`rowCount`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param FeatureEffectCreateJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(FeatureEffectCreateJson, validateParams = FALSE) {
      FeatureEffectCreateObject <- jsonlite::fromJSON(FeatureEffectCreateJson)
      self$`rowCount` <- FeatureEffectCreateObject$`rowCount`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
