# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FileSystemIntake
#'
#' @description FileSystemIntake Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field path  character Path to data on host filesystem
#'
#' @field type  character Type name for this intake type
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FileSystemIntake <- R6::R6Class(
  "FileSystemIntake",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`path` = NULL, `type` = NULL) {
      if (!is.null(`path`)) {
        stopifnot(is.character(`path`), length(`path`) == 1)
      }
      if (!is.null(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
      }
    }
  ),
  public = list(
    `path` = NULL,
    `type` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param path Path to data on host filesystem
    #' @param type Type name for this intake type
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`path` = NULL, `type` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`path`, `type`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(path, type)
      }
      self$`path` <- `path`
      self$`type` <- `type`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(path = self$`path`, type = self$`type`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`path`)) {
          sprintf(
            '"path":
            "%s"
                  ',
            self$`path`
          )
        },
        if (!is.null(self$`type`)) {
          sprintf(
            '"type":
            "%s"
                  ',
            self$`type`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param FileSystemIntakeJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(FileSystemIntakeJson, validateParams = FALSE) {
      FileSystemIntakeObject <- jsonlite::fromJSON(FileSystemIntakeJson)
      self$`path` <- FileSystemIntakeObject$`path`
      self$`type` <- FileSystemIntakeObject$`type`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
