# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ForecastDistancePlotDataEntryResponse
#'
#' @description ForecastDistancePlotDataEntryResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field backtestingScore  numeric Backtesting score for this forecast distance. If backtesting has not been run for this model, this score will be &#x60;null&#x60;.
#'
#' @field forecastDistance  integer The number of time units the scored rows are away from the forecast point.
#'
#' @field holdoutScore  numeric Holdout set score for this forecast distance. If holdout is locked for the project, this score will be &#x60;null&#x60;.
#'
#' @field validationScore  numeric Validation set score for this forecast distance.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ForecastDistancePlotDataEntryResponse <- R6::R6Class(
  "ForecastDistancePlotDataEntryResponse",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`backtestingScore` = NULL, `forecastDistance` = NULL, `holdoutScore` = NULL, `validationScore` = NULL) {
      if (!is.null(`backtestingScore`)) {
      }
      if (!is.null(`forecastDistance`)) {
        stopifnot(is.numeric(`forecastDistance`), length(`forecastDistance`) == 1)
      }
      if (!is.null(`holdoutScore`)) {
      }
      if (!is.null(`validationScore`)) {
      }
    }
  ),
  public = list(
    `backtestingScore` = NULL,
    `forecastDistance` = NULL,
    `holdoutScore` = NULL,
    `validationScore` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param backtestingScore Backtesting score for this forecast distance. If backtesting has not been run for this model, this score will be &#x60;null&#x60;.
    #' @param forecastDistance The number of time units the scored rows are away from the forecast point.
    #' @param holdoutScore Holdout set score for this forecast distance. If holdout is locked for the project, this score will be &#x60;null&#x60;.
    #' @param validationScore Validation set score for this forecast distance.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`backtestingScore` = NULL, `forecastDistance` = NULL, `holdoutScore` = NULL, `validationScore` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`backtestingScore`, `forecastDistance`, `holdoutScore`, `validationScore`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(backtestingScore, forecastDistance, holdoutScore, validationScore)
      }
      self$`backtestingScore` <- `backtestingScore`
      self$`forecastDistance` <- `forecastDistance`
      self$`holdoutScore` <- `holdoutScore`
      self$`validationScore` <- `validationScore`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(backtestingScore = self$`backtestingScore`, forecastDistance = self$`forecastDistance`, holdoutScore = self$`holdoutScore`, validationScore = self$`validationScore`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`backtestingScore`)) {
          sprintf(
            '"backtestingScore":
            %d
                  ',
            self$`backtestingScore`
          )
        },
        if (!is.null(self$`forecastDistance`)) {
          sprintf(
            '"forecastDistance":
            %d
                  ',
            self$`forecastDistance`
          )
        },
        if (!is.null(self$`holdoutScore`)) {
          sprintf(
            '"holdoutScore":
            %d
                  ',
            self$`holdoutScore`
          )
        },
        if (!is.null(self$`validationScore`)) {
          sprintf(
            '"validationScore":
            %d
                  ',
            self$`validationScore`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param ForecastDistancePlotDataEntryResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(ForecastDistancePlotDataEntryResponseJson, validateParams = FALSE) {
      ForecastDistancePlotDataEntryResponseObject <- jsonlite::fromJSON(ForecastDistancePlotDataEntryResponseJson)
      self$`backtestingScore` <- ForecastDistancePlotDataEntryResponseObject$`backtestingScore`
      self$`forecastDistance` <- ForecastDistancePlotDataEntryResponseObject$`forecastDistance`
      self$`holdoutScore` <- ForecastDistancePlotDataEntryResponseObject$`holdoutScore`
      self$`validationScore` <- ForecastDistancePlotDataEntryResponseObject$`validationScore`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
