# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title GrantAccessControlWithUsernameWithGrant
#'
#' @description GrantAccessControlWithUsernameWithGrant Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field canShare  character [optional] Whether the org/group/user should be able to share with others.If true, the org/group/user will be able to grant any role up to and includingtheir own to other orgs/groups/user. If &#x60;role&#x60; is &#x60;NO_ROLE&#x60; &#x60;canShare&#x60; is ignored.
#'
#' @field role  character The role of the recipient on this entity. One of OWNER, USER, OBSERVER.
#'
#' @field shareRecipientType  character Describes the recipient type, either user, group, or organization.
#'
#' @field username  character Username of the user to update the access role for.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GrantAccessControlWithUsernameWithGrant <- R6::R6Class(
  "GrantAccessControlWithUsernameWithGrant",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`canShare` = NULL, `role` = NULL, `shareRecipientType` = NULL, `username` = NULL) {
      if (!is.null(`role`)) {
        stopifnot(is.character(`role`), length(`role`) == 1)
      }
      if (!is.null(`shareRecipientType`)) {
        stopifnot(is.character(`shareRecipientType`), length(`shareRecipientType`) == 1)
      }
      if (!is.null(`username`)) {
        stopifnot(is.character(`username`), length(`username`) == 1)
      }
      if (!is.null(`canShare`)) {
        stopifnot(is.logical(`canShare`), length(`canShare`) == 1)
      }
    }
  ),
  public = list(
    `canShare` = NULL,
    `role` = NULL,
    `shareRecipientType` = NULL,
    `username` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param canShare Whether the org/group/user should be able to share with others.If true, the org/group/user will be able to grant any role up to and includingtheir own to other orgs/groups/user. If &#x60;role&#x60; is &#x60;NO_ROLE&#x60; &#x60;canShare&#x60; is ignored.
    #' @param role The role of the recipient on this entity. One of OWNER, USER, OBSERVER.
    #' @param shareRecipientType Describes the recipient type, either user, group, or organization.
    #' @param username Username of the user to update the access role for.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`role` = NULL, `shareRecipientType` = NULL, `username` = NULL, `canShare` = TRUE, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`role`, `shareRecipientType`, `username`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(canShare, role, shareRecipientType, username)
      }
      self$`canShare` <- `canShare`
      self$`role` <- `role`
      self$`shareRecipientType` <- `shareRecipientType`
      self$`username` <- `username`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(canShare = self$`canShare`, role = self$`role`, shareRecipientType = self$`shareRecipientType`, username = self$`username`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`canShare`)) {
          sprintf(
            '"canShare":
            %s
                  ',
            tolower(self$`canShare`)
          )
        },
        if (!is.null(self$`role`)) {
          sprintf(
            '"role":
            "%s"
                  ',
            self$`role`
          )
        },
        if (!is.null(self$`shareRecipientType`)) {
          sprintf(
            '"shareRecipientType":
            "%s"
                  ',
            self$`shareRecipientType`
          )
        },
        if (!is.null(self$`username`)) {
          sprintf(
            '"username":
            "%s"
                  ',
            self$`username`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param GrantAccessControlWithUsernameWithGrantJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(GrantAccessControlWithUsernameWithGrantJson, validateParams = FALSE) {
      GrantAccessControlWithUsernameWithGrantObject <- jsonlite::fromJSON(GrantAccessControlWithUsernameWithGrantJson)
      self$`canShare` <- GrantAccessControlWithUsernameWithGrantObject$`canShare`
      self$`role` <- GrantAccessControlWithUsernameWithGrantObject$`role`
      self$`shareRecipientType` <- GrantAccessControlWithUsernameWithGrantObject$`shareRecipientType`
      self$`username` <- GrantAccessControlWithUsernameWithGrantObject$`username`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
