# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title HTTPOutput
#'
#' @description HTTPOutput Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field headers  object [optional] Extra headers to send with the request
#'
#' @field method  character Method to use when saving the CSV file
#'
#' @field type  character Type name for this output type
#'
#' @field url  character URL for the CSV file
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
HTTPOutput <- R6::R6Class(
  "HTTPOutput",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`headers` = NULL, `method` = NULL, `type` = NULL, `url` = NULL) {
      if (!is.null(`method`)) {
        stopifnot(is.character(`method`), length(`method`) == 1)
      }
      if (!is.null(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
      }
      if (!is.null(`url`)) {
        stopifnot(is.character(`url`), length(`url`) == 1)
      }
      if (!is.null(`headers`)) {
      }
    }
  ),
  public = list(
    `headers` = NULL,
    `method` = NULL,
    `type` = NULL,
    `url` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param headers Extra headers to send with the request
    #' @param method Method to use when saving the CSV file
    #' @param type Type name for this output type
    #' @param url URL for the CSV file
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`method` = NULL, `type` = NULL, `url` = NULL, `headers` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`method`, `type`, `url`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(headers, method, type, url)
      }
      self$`headers` <- `headers`
      self$`method` <- `method`
      self$`type` <- `type`
      self$`url` <- `url`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(headers = self$`headers`, method = self$`method`, type = self$`type`, url = self$`url`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`headers`)) {
          sprintf(
            '"headers":
            "%s"
                  ',
            self$`headers`
          )
        },
        if (!is.null(self$`method`)) {
          sprintf(
            '"method":
            "%s"
                  ',
            self$`method`
          )
        },
        if (!is.null(self$`type`)) {
          sprintf(
            '"type":
            "%s"
                  ',
            self$`type`
          )
        },
        if (!is.null(self$`url`)) {
          sprintf(
            '"url":
            "%s"
                  ',
            self$`url`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param HTTPOutputJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(HTTPOutputJson, validateParams = FALSE) {
      HTTPOutputObject <- jsonlite::fromJSON(HTTPOutputJson)
      self$`headers` <- HTTPOutputObject$`headers`
      self$`method` <- HTTPOutputObject$`method`
      self$`type` <- HTTPOutputObject$`type`
      self$`url` <- HTTPOutputObject$`url`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
