# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModelPackageImportMeta
#'
#' @description ModelPackageImportMeta Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field containsFearPipeline  character [optional] Exists for imported models only, indicates thatmodel package contains file with fear pipeline.
#'
#' @field containsFeaturelists  character [optional] Exists for imported models only, indicates thatmodel package contains file with featurelists.
#'
#' @field containsLeaderboardMeta  character [optional] Exists for imported models only, indicates thatmodel package contains file with leaderboard meta.
#'
#' @field containsProjectMeta  character [optional] Exists for imported models only, indicates thatmodel package contains file with project meta.
#'
#' @field creatorId  character User ID of the person who created this Model Package
#'
#' @field creatorUsername  character Username of the person who created this model package
#'
#' @field dateCreated  character When this Model Package was created
#'
#' @field originalFileName  character Exists for imported models only, the original file name that was uploaded
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModelPackageImportMeta <- R6::R6Class(
  "ModelPackageImportMeta",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`containsFearPipeline` = NULL, `containsFeaturelists` = NULL, `containsLeaderboardMeta` = NULL, `containsProjectMeta` = NULL, `creatorId` = NULL, `creatorUsername` = NULL, `dateCreated` = NULL, `originalFileName` = NULL) {
      if (!is.null(`creatorId`)) {
        stopifnot(is.character(`creatorId`), length(`creatorId`) == 1)
      }
      if (!is.null(`creatorUsername`)) {
        stopifnot(is.character(`creatorUsername`), length(`creatorUsername`) == 1)
      }
      if (!is.null(`dateCreated`)) {
        stopifnot(is.character(`dateCreated`), length(`dateCreated`) == 1)
      }
      if (!is.null(`originalFileName`)) {
        stopifnot(is.character(`originalFileName`), length(`originalFileName`) == 1)
      }
      if (!is.null(`containsFearPipeline`)) {
        stopifnot(is.character(`containsFearPipeline`), length(`containsFearPipeline`) == 1)
      }
      if (!is.null(`containsFeaturelists`)) {
        stopifnot(is.character(`containsFeaturelists`), length(`containsFeaturelists`) == 1)
      }
      if (!is.null(`containsLeaderboardMeta`)) {
        stopifnot(is.character(`containsLeaderboardMeta`), length(`containsLeaderboardMeta`) == 1)
      }
      if (!is.null(`containsProjectMeta`)) {
        stopifnot(is.character(`containsProjectMeta`), length(`containsProjectMeta`) == 1)
      }
    }
  ),
  public = list(
    `containsFearPipeline` = NULL,
    `containsFeaturelists` = NULL,
    `containsLeaderboardMeta` = NULL,
    `containsProjectMeta` = NULL,
    `creatorId` = NULL,
    `creatorUsername` = NULL,
    `dateCreated` = NULL,
    `originalFileName` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param containsFearPipeline Exists for imported models only, indicates thatmodel package contains file with fear pipeline.
    #' @param containsFeaturelists Exists for imported models only, indicates thatmodel package contains file with featurelists.
    #' @param containsLeaderboardMeta Exists for imported models only, indicates thatmodel package contains file with leaderboard meta.
    #' @param containsProjectMeta Exists for imported models only, indicates thatmodel package contains file with project meta.
    #' @param creatorId User ID of the person who created this Model Package
    #' @param creatorUsername Username of the person who created this model package
    #' @param dateCreated When this Model Package was created
    #' @param originalFileName Exists for imported models only, the original file name that was uploaded
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`creatorId` = NULL, `creatorUsername` = NULL, `dateCreated` = NULL, `originalFileName` = NULL, `containsFearPipeline` = NULL, `containsFeaturelists` = NULL, `containsLeaderboardMeta` = NULL, `containsProjectMeta` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`creatorId`, `creatorUsername`, `dateCreated`, `originalFileName`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(containsFearPipeline, containsFeaturelists, containsLeaderboardMeta, containsProjectMeta, creatorId, creatorUsername, dateCreated, originalFileName)
      }
      self$`containsFearPipeline` <- `containsFearPipeline`
      self$`containsFeaturelists` <- `containsFeaturelists`
      self$`containsLeaderboardMeta` <- `containsLeaderboardMeta`
      self$`containsProjectMeta` <- `containsProjectMeta`
      self$`creatorId` <- `creatorId`
      self$`creatorUsername` <- `creatorUsername`
      self$`dateCreated` <- `dateCreated`
      self$`originalFileName` <- `originalFileName`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(containsFearPipeline = self$`containsFearPipeline`, containsFeaturelists = self$`containsFeaturelists`, containsLeaderboardMeta = self$`containsLeaderboardMeta`, containsProjectMeta = self$`containsProjectMeta`, creatorId = self$`creatorId`, creatorUsername = self$`creatorUsername`, dateCreated = self$`dateCreated`, originalFileName = self$`originalFileName`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`containsFearPipeline`)) {
          sprintf(
            '"containsFearPipeline":
            "%s"
                  ',
            self$`containsFearPipeline`
          )
        },
        if (!is.null(self$`containsFeaturelists`)) {
          sprintf(
            '"containsFeaturelists":
            "%s"
                  ',
            self$`containsFeaturelists`
          )
        },
        if (!is.null(self$`containsLeaderboardMeta`)) {
          sprintf(
            '"containsLeaderboardMeta":
            "%s"
                  ',
            self$`containsLeaderboardMeta`
          )
        },
        if (!is.null(self$`containsProjectMeta`)) {
          sprintf(
            '"containsProjectMeta":
            "%s"
                  ',
            self$`containsProjectMeta`
          )
        },
        if (!is.null(self$`creatorId`)) {
          sprintf(
            '"creatorId":
            "%s"
                  ',
            self$`creatorId`
          )
        },
        if (!is.null(self$`creatorUsername`)) {
          sprintf(
            '"creatorUsername":
            "%s"
                  ',
            self$`creatorUsername`
          )
        },
        if (!is.null(self$`dateCreated`)) {
          sprintf(
            '"dateCreated":
            "%s"
                  ',
            self$`dateCreated`
          )
        },
        if (!is.null(self$`originalFileName`)) {
          sprintf(
            '"originalFileName":
            "%s"
                  ',
            self$`originalFileName`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param ModelPackageImportMetaJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(ModelPackageImportMetaJson, validateParams = FALSE) {
      ModelPackageImportMetaObject <- jsonlite::fromJSON(ModelPackageImportMetaJson)
      self$`containsFearPipeline` <- ModelPackageImportMetaObject$`containsFearPipeline`
      self$`containsFeaturelists` <- ModelPackageImportMetaObject$`containsFeaturelists`
      self$`containsLeaderboardMeta` <- ModelPackageImportMetaObject$`containsLeaderboardMeta`
      self$`containsProjectMeta` <- ModelPackageImportMetaObject$`containsProjectMeta`
      self$`creatorId` <- ModelPackageImportMetaObject$`creatorId`
      self$`creatorUsername` <- ModelPackageImportMetaObject$`creatorUsername`
      self$`dateCreated` <- ModelPackageImportMetaObject$`dateCreated`
      self$`originalFileName` <- ModelPackageImportMetaObject$`originalFileName`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
