# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModelXrayCreateDatetime
#'
#' @description ModelXrayCreateDatetime Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field backtestIndex  character The backtest index. For example: &#x60;0&#x60;, &#x60;1&#x60;, ..., &#x60;20&#x60;, &#x60;holdout&#x60;, &#x60;startstop&#x60;.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModelXrayCreateDatetime <- R6::R6Class(
  "ModelXrayCreateDatetime",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`backtestIndex` = NULL) {
      if (!is.null(`backtestIndex`)) {
        stopifnot(is.character(`backtestIndex`), length(`backtestIndex`) == 1)
      }
    }
  ),
  public = list(
    `backtestIndex` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param backtestIndex The backtest index. For example: &#x60;0&#x60;, &#x60;1&#x60;, ..., &#x60;20&#x60;, &#x60;holdout&#x60;, &#x60;startstop&#x60;.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`backtestIndex` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`backtestIndex`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(backtestIndex)
      }
      self$`backtestIndex` <- `backtestIndex`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(backtestIndex = self$`backtestIndex`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`backtestIndex`)) {
          sprintf(
            '"backtestIndex":
            "%s"
                  ',
            self$`backtestIndex`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param ModelXrayCreateDatetimeJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(ModelXrayCreateDatetimeJson, validateParams = FALSE) {
      ModelXrayCreateDatetimeObject <- jsonlite::fromJSON(ModelXrayCreateDatetimeJson)
      self$`backtestIndex` <- ModelXrayCreateDatetimeObject$`backtestIndex`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
