# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ModelPackageResponse
#'
#' @description ModelPackageResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character ID of the model package.
#'
#' @field name  character Type of the current model.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModelPackageResponse <- R6::R6Class(
  "ModelPackageResponse",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(id = NULL, name = NULL) {
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
      }
    }
  ),
  public = list(
    `id` = NULL,
    `name` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param id ID of the model package.
    #' @param name Type of the current model.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`id` = NULL, `name` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`id`, `name`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(id, name)
      }
      self$`id` <- `id`
      self$`name` <- `name`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(id = self$`id`, name = self$`name`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
          sprintf(
            '"id":
            "%s"
                  ',
            self$`id`
          )
        },
        if (!is.null(self$`name`)) {
          sprintf(
            '"name":
            "%s"
                  ',
            self$`name`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param ModelPackageResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(ModelPackageResponseJson, validateParams = FALSE) {
      ModelPackageResponseObject <- jsonlite::fromJSON(ModelPackageResponseJson)
      self$`id` <- ModelPackageResponseObject$`id`
      self$`name` <- ModelPackageResponseObject$`name`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
