# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MulticlassFeatureEffectDatetimeCreate
#'
#' @description MulticlassFeatureEffectDatetimeCreate Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field backtestIndex  character The backtest index. For example: &#x60;0&#x60;, &#x60;1&#x60;, ..., &#x60;20&#x60;, &#x60;holdout&#x60;, &#x60;startstop&#x60;.
#'
#' @field features  list( character ) [optional] The list of features to use to calculate feature effects.
#'
#' @field rowCount  integer [optional] The number of rows from dataset to use for Feature Impact calculation.
#'
#' @field topNFeatures  integer [optional] Number of top features (ranked by feature impact) to use to calculate feature effects.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MulticlassFeatureEffectDatetimeCreate <- R6::R6Class(
  "MulticlassFeatureEffectDatetimeCreate",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`backtestIndex` = NULL, `features` = NULL, `rowCount` = NULL, `topNFeatures` = NULL) {
      if (!is.null(`backtestIndex`)) {
        stopifnot(is.character(`backtestIndex`), length(`backtestIndex`) == 1)
      }
      if (!is.null(`features`) && length(`features`) > 0) {
        stopifnot(is.vector(`features`), sapply(`features`, is.character))
      }
      if (!is.null(`rowCount`)) {
        stopifnot(is.numeric(`rowCount`), length(`rowCount`) == 1)
      }
      if (!is.null(`topNFeatures`)) {
        stopifnot(is.numeric(`topNFeatures`), length(`topNFeatures`) == 1)
      }
    }
  ),
  public = list(
    `backtestIndex` = NULL,
    `features` = NULL,
    `rowCount` = NULL,
    `topNFeatures` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param backtestIndex The backtest index. For example: &#x60;0&#x60;, &#x60;1&#x60;, ..., &#x60;20&#x60;, &#x60;holdout&#x60;, &#x60;startstop&#x60;.
    #' @param features The list of features to use to calculate feature effects.
    #' @param rowCount The number of rows from dataset to use for Feature Impact calculation.
    #' @param topNFeatures Number of top features (ranked by feature impact) to use to calculate feature effects.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`backtestIndex` = NULL, `features` = NULL, `rowCount` = NULL, `topNFeatures` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`backtestIndex`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(backtestIndex, features, rowCount, topNFeatures)
      }
      self$`backtestIndex` <- `backtestIndex`
      self$`features` <- `features`
      self$`rowCount` <- `rowCount`
      self$`topNFeatures` <- `topNFeatures`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(backtestIndex = self$`backtestIndex`, features = self$`features`, rowCount = self$`rowCount`, topNFeatures = self$`topNFeatures`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`backtestIndex`)) {
          sprintf(
            '"backtestIndex":
            "%s"
                  ',
            self$`backtestIndex`
          )
        },
        if (!is.null(self$`features`)) {
          sprintf(
            '"features":
            [%s]
                  ',
            paste(unlist(lapply(self$`features`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`rowCount`)) {
          sprintf(
            '"rowCount":
            %d
                  ',
            self$`rowCount`
          )
        },
        if (!is.null(self$`topNFeatures`)) {
          sprintf(
            '"topNFeatures":
            %d
                  ',
            self$`topNFeatures`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param MulticlassFeatureEffectDatetimeCreateJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(MulticlassFeatureEffectDatetimeCreateJson, validateParams = FALSE) {
      MulticlassFeatureEffectDatetimeCreateObject <- jsonlite::fromJSON(MulticlassFeatureEffectDatetimeCreateJson)
      self$`backtestIndex` <- MulticlassFeatureEffectDatetimeCreateObject$`backtestIndex`
      self$`features` <- ApiClient$new()$deserializeObj(MulticlassFeatureEffectDatetimeCreateObject$`features`, "array[character]", loadNamespace("datarobot.apicore"))
      self$`rowCount` <- MulticlassFeatureEffectDatetimeCreateObject$`rowCount`
      self$`topNFeatures` <- MulticlassFeatureEffectDatetimeCreateObject$`topNFeatures`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
