# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title OptionalJDBCTableDataSource
#'
#' @description OptionalJDBCTableDataSource Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field catalog  character [optional] Catalog name in the database if supported.
#'
#' @field dataStoreId  character [optional] Data store ID for this data source.
#'
#' @field fetchSize  integer [optional] User-specified fetch size.
#'
#' @field partitionColumn  character [optional] The name of the partition column. It is needed to allow parallel execution for the 10GB+ projects.
#'
#' @field schema  character [optional] Schema associated with the table or view in the database if supported.
#'
#' @field table  character [optional] Table or view name in the database.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OptionalJDBCTableDataSource <- R6::R6Class(
  "OptionalJDBCTableDataSource",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`catalog` = NULL, `dataStoreId` = NULL, `fetchSize` = NULL, `partitionColumn` = NULL, `schema` = NULL, `table` = NULL) {
      if (!is.null(`catalog`)) {
        stopifnot(is.character(`catalog`), length(`catalog`) == 1)
      }
      if (!is.null(`dataStoreId`)) {
        stopifnot(is.character(`dataStoreId`), length(`dataStoreId`) == 1)
      }
      if (!is.null(`fetchSize`)) {
        stopifnot(is.numeric(`fetchSize`), length(`fetchSize`) == 1)
      }
      if (!is.null(`partitionColumn`)) {
        stopifnot(is.character(`partitionColumn`), length(`partitionColumn`) == 1)
      }
      if (!is.null(`schema`)) {
        stopifnot(is.character(`schema`), length(`schema`) == 1)
      }
      if (!is.null(`table`)) {
        stopifnot(is.character(`table`), length(`table`) == 1)
      }
    }
  ),
  public = list(
    `catalog` = NULL,
    `dataStoreId` = NULL,
    `fetchSize` = NULL,
    `partitionColumn` = NULL,
    `schema` = NULL,
    `table` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param catalog Catalog name in the database if supported.
    #' @param dataStoreId Data store ID for this data source.
    #' @param fetchSize User-specified fetch size.
    #' @param partitionColumn The name of the partition column. It is needed to allow parallel execution for the 10GB+ projects.
    #' @param schema Schema associated with the table or view in the database if supported.
    #' @param table Table or view name in the database.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`catalog` = NULL, `dataStoreId` = NULL, `fetchSize` = NULL, `partitionColumn` = NULL, `schema` = NULL, `table` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(catalog, dataStoreId, fetchSize, partitionColumn, schema, table)
      }
      self$`catalog` <- `catalog`
      self$`dataStoreId` <- `dataStoreId`
      self$`fetchSize` <- `fetchSize`
      self$`partitionColumn` <- `partitionColumn`
      self$`schema` <- `schema`
      self$`table` <- `table`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(catalog = self$`catalog`, dataStoreId = self$`dataStoreId`, fetchSize = self$`fetchSize`, partitionColumn = self$`partitionColumn`, schema = self$`schema`, table = self$`table`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`catalog`)) {
          sprintf(
            '"catalog":
            "%s"
                  ',
            self$`catalog`
          )
        },
        if (!is.null(self$`dataStoreId`)) {
          sprintf(
            '"dataStoreId":
            "%s"
                  ',
            self$`dataStoreId`
          )
        },
        if (!is.null(self$`fetchSize`)) {
          sprintf(
            '"fetchSize":
            %d
                  ',
            self$`fetchSize`
          )
        },
        if (!is.null(self$`partitionColumn`)) {
          sprintf(
            '"partitionColumn":
            "%s"
                  ',
            self$`partitionColumn`
          )
        },
        if (!is.null(self$`schema`)) {
          sprintf(
            '"schema":
            "%s"
                  ',
            self$`schema`
          )
        },
        if (!is.null(self$`table`)) {
          sprintf(
            '"table":
            "%s"
                  ',
            self$`table`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param OptionalJDBCTableDataSourceJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(OptionalJDBCTableDataSourceJson, validateParams = FALSE) {
      OptionalJDBCTableDataSourceObject <- jsonlite::fromJSON(OptionalJDBCTableDataSourceJson)
      self$`catalog` <- OptionalJDBCTableDataSourceObject$`catalog`
      self$`dataStoreId` <- OptionalJDBCTableDataSourceObject$`dataStoreId`
      self$`fetchSize` <- OptionalJDBCTableDataSourceObject$`fetchSize`
      self$`partitionColumn` <- OptionalJDBCTableDataSourceObject$`partitionColumn`
      self$`schema` <- OptionalJDBCTableDataSourceObject$`schema`
      self$`table` <- OptionalJDBCTableDataSourceObject$`table`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
