# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PairwiseManualSelectionCreatePayload
#'
#' @description PairwiseManualSelectionCreatePayload Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field columnLabels  list( character ) Manually selected column labels.
#'
#' @field featureName  character Name of the feature the request is related to
#'
#' @field multilabelInsightsKey  character Key for multilabel insights, unique per project, feature, and EDA stage. The most recent key can be retrieved via :http:get:&#x60;/api/v2/projects/(projectId)/features/&#x60; or :http:get:&#x60;/api/v2/projects/(projectId)/features/(featurename:featureName)/&#x60;
#'
#' @field name  character Name for the set of manually selected labels.
#'
#' @field projectId  character ID of the project the request is related to.
#'
#' @field rowLabels  list( character ) Manually selected row labels.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PairwiseManualSelectionCreatePayload <- R6::R6Class(
  "PairwiseManualSelectionCreatePayload",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`columnLabels` = NULL, `featureName` = NULL, `multilabelInsightsKey` = NULL, `name` = NULL, `projectId` = NULL, `rowLabels` = NULL) {
      if (!is.null(`columnLabels`)) {
        stopifnot(is.vector(`columnLabels`), sapply(`columnLabels`, is.character))
      }
      if (!is.null(`featureName`)) {
        stopifnot(is.character(`featureName`), length(`featureName`) == 1)
      }
      if (!is.null(`multilabelInsightsKey`)) {
        stopifnot(is.character(`multilabelInsightsKey`), length(`multilabelInsightsKey`) == 1)
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
      }
      if (!is.null(`projectId`)) {
        stopifnot(is.character(`projectId`), length(`projectId`) == 1)
      }
      if (!is.null(`rowLabels`)) {
        stopifnot(is.vector(`rowLabels`), sapply(`rowLabels`, is.character))
      }
    }
  ),
  public = list(
    `columnLabels` = NULL,
    `featureName` = NULL,
    `multilabelInsightsKey` = NULL,
    `name` = NULL,
    `projectId` = NULL,
    `rowLabels` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param columnLabels Manually selected column labels.
    #' @param featureName Name of the feature the request is related to
    #' @param multilabelInsightsKey Key for multilabel insights, unique per project, feature, and EDA stage. The most recent key can be retrieved via :http:get:&#x60;/api/v2/projects/(projectId)/features/&#x60; or :http:get:&#x60;/api/v2/projects/(projectId)/features/(featurename:featureName)/&#x60;
    #' @param name Name for the set of manually selected labels.
    #' @param projectId ID of the project the request is related to.
    #' @param rowLabels Manually selected row labels.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`columnLabels` = NULL, `featureName` = NULL, `multilabelInsightsKey` = NULL, `name` = NULL, `projectId` = NULL, `rowLabels` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`columnLabels`, `featureName`, `multilabelInsightsKey`, `name`, `projectId`, `rowLabels`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(columnLabels, featureName, multilabelInsightsKey, name, projectId, rowLabels)
      }
      self$`columnLabels` <- `columnLabels`
      self$`featureName` <- `featureName`
      self$`multilabelInsightsKey` <- `multilabelInsightsKey`
      self$`name` <- `name`
      self$`projectId` <- `projectId`
      self$`rowLabels` <- `rowLabels`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(columnLabels = self$`columnLabels`, featureName = self$`featureName`, multilabelInsightsKey = self$`multilabelInsightsKey`, name = self$`name`, projectId = self$`projectId`, rowLabels = self$`rowLabels`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`columnLabels`)) {
          sprintf(
            '"columnLabels":
            [%s]
                  ',
            paste(unlist(lapply(self$`columnLabels`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`featureName`)) {
          sprintf(
            '"featureName":
            "%s"
                  ',
            self$`featureName`
          )
        },
        if (!is.null(self$`multilabelInsightsKey`)) {
          sprintf(
            '"multilabelInsightsKey":
            "%s"
                  ',
            self$`multilabelInsightsKey`
          )
        },
        if (!is.null(self$`name`)) {
          sprintf(
            '"name":
            "%s"
                  ',
            self$`name`
          )
        },
        if (!is.null(self$`projectId`)) {
          sprintf(
            '"projectId":
            "%s"
                  ',
            self$`projectId`
          )
        },
        if (!is.null(self$`rowLabels`)) {
          sprintf(
            '"rowLabels":
            [%s]
                  ',
            paste(unlist(lapply(self$`rowLabels`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param PairwiseManualSelectionCreatePayloadJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(PairwiseManualSelectionCreatePayloadJson, validateParams = FALSE) {
      PairwiseManualSelectionCreatePayloadObject <- jsonlite::fromJSON(PairwiseManualSelectionCreatePayloadJson)
      self$`columnLabels` <- ApiClient$new()$deserializeObj(PairwiseManualSelectionCreatePayloadObject$`columnLabels`, "array[character]", loadNamespace("datarobot.apicore"))
      self$`featureName` <- PairwiseManualSelectionCreatePayloadObject$`featureName`
      self$`multilabelInsightsKey` <- PairwiseManualSelectionCreatePayloadObject$`multilabelInsightsKey`
      self$`name` <- PairwiseManualSelectionCreatePayloadObject$`name`
      self$`projectId` <- PairwiseManualSelectionCreatePayloadObject$`projectId`
      self$`rowLabels` <- ApiClient$new()$deserializeObj(PairwiseManualSelectionCreatePayloadObject$`rowLabels`, "array[character]", loadNamespace("datarobot.apicore"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
