# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PredictedPercentages
#'
#' @description PredictedPercentages Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field otherClassName  character the name of the class
#'
#' @field percentage  numeric the percentage of the times this class was actual when &#x60;classMetrics.className&#x60; is predicted
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PredictedPercentages <- R6::R6Class(
  "PredictedPercentages",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(otherClassName = NULL, percentage = NULL) {
      if (!is.null(`otherClassName`)) {
        stopifnot(is.character(`otherClassName`), length(`otherClassName`) == 1)
      }
      if (!is.null(`percentage`)) {
      }
    }
  ),
  public = list(
    `otherClassName` = NULL,
    `percentage` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param otherClassName the name of the class
    #' @param percentage the percentage of the times this class was actual when &#x60;classMetrics.className&#x60; is predicted
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`otherClassName` = NULL, `percentage` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`otherClassName`, `percentage`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(otherClassName, percentage)
      }
      self$`otherClassName` <- `otherClassName`
      self$`percentage` <- `percentage`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(otherClassName = self$`otherClassName`, percentage = self$`percentage`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`otherClassName`)) {
          sprintf(
            '"otherClassName":
            "%s"
                  ',
            self$`otherClassName`
          )
        },
        if (!is.null(self$`percentage`)) {
          sprintf(
            '"percentage":
            %d
                  ',
            self$`percentage`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param PredictedPercentagesJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(PredictedPercentagesJson, validateParams = FALSE) {
      PredictedPercentagesObject <- jsonlite::fromJSON(PredictedPercentagesJson)
      self$`otherClassName` <- PredictedPercentagesObject$`otherClassName`
      self$`percentage` <- PredictedPercentagesObject$`percentage`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
