# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ProjectNukeJobStatusSummaryObject
#'
#' @description ProjectNukeJobStatusSummaryObject Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field aborted  integer Number of project permadelete jobs with Aborted status.
#'
#' @field completed  integer Number of project permadelete jobs with Completed status.
#'
#' @field error  integer Number of project permadelete jobs with Error status.
#'
#' @field expired  integer Number of project permadelete jobs with Expired status.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ProjectNukeJobStatusSummaryObject <- R6::R6Class(
  "ProjectNukeJobStatusSummaryObject",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`aborted` = NULL, `completed` = NULL, `error` = NULL, `expired` = NULL) {
      if (!is.null(`aborted`)) {
        stopifnot(is.numeric(`aborted`), length(`aborted`) == 1)
      }
      if (!is.null(`completed`)) {
        stopifnot(is.numeric(`completed`), length(`completed`) == 1)
      }
      if (!is.null(`error`)) {
        stopifnot(is.numeric(`error`), length(`error`) == 1)
      }
      if (!is.null(`expired`)) {
        stopifnot(is.numeric(`expired`), length(`expired`) == 1)
      }
    }
  ),
  public = list(
    `aborted` = NULL,
    `completed` = NULL,
    `error` = NULL,
    `expired` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param aborted Number of project permadelete jobs with Aborted status.
    #' @param completed Number of project permadelete jobs with Completed status.
    #' @param error Number of project permadelete jobs with Error status.
    #' @param expired Number of project permadelete jobs with Expired status.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`aborted` = NULL, `completed` = NULL, `error` = NULL, `expired` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`aborted`, `completed`, `error`, `expired`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(aborted, completed, error, expired)
      }
      self$`aborted` <- `aborted`
      self$`completed` <- `completed`
      self$`error` <- `error`
      self$`expired` <- `expired`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(aborted = self$`aborted`, completed = self$`completed`, error = self$`error`, expired = self$`expired`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`aborted`)) {
          sprintf(
            '"aborted":
            %d
                  ',
            self$`aborted`
          )
        },
        if (!is.null(self$`completed`)) {
          sprintf(
            '"completed":
            %d
                  ',
            self$`completed`
          )
        },
        if (!is.null(self$`error`)) {
          sprintf(
            '"error":
            %d
                  ',
            self$`error`
          )
        },
        if (!is.null(self$`expired`)) {
          sprintf(
            '"expired":
            %d
                  ',
            self$`expired`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param ProjectNukeJobStatusSummaryObjectJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(ProjectNukeJobStatusSummaryObjectJson, validateParams = FALSE) {
      ProjectNukeJobStatusSummaryObjectObject <- jsonlite::fromJSON(ProjectNukeJobStatusSummaryObjectJson)
      self$`aborted` <- ProjectNukeJobStatusSummaryObjectObject$`aborted`
      self$`completed` <- ProjectNukeJobStatusSummaryObjectObject$`completed`
      self$`error` <- ProjectNukeJobStatusSummaryObjectObject$`error`
      self$`expired` <- ProjectNukeJobStatusSummaryObjectObject$`expired`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
