# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ProjectNuke
#'
#' @description ProjectNuke Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field creator  character [optional] Creator ID to filter projects by
#'
#' @field deletedAfter  character [optional] ISO-8601 formatted date projects were deleted after
#'
#' @field deletedBefore  character [optional] ISO-8601 formatted date projects were deleted before
#'
#' @field limit  integer [optional] At most this many projects are deleted.
#'
#' @field offset  integer [optional] This many projects will be skipped.
#'
#' @field organization  character [optional] ID of organization that projects should belong to
#'
#' @field projectIds  list( character ) [optional] List of project IDs to delete permanently.
#'
#' @field searchFor  character [optional] Project or dataset name to filter by
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ProjectNuke <- R6::R6Class(
  "ProjectNuke",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(creator = NULL, deletedAfter = NULL, deletedBefore = NULL, limit = NULL, offset = NULL, organization = NULL, projectIds = NULL, searchFor = NULL) {
      if (!is.null(`creator`)) {
        stopifnot(is.character(`creator`), length(`creator`) == 1)
      }
      if (!is.null(`deletedAfter`)) {
        stopifnot(inherits(`deletedAfter`, "POSIXt"))
      }
      if (!is.null(`deletedBefore`)) {
        stopifnot(inherits(`deletedBefore`, "POSIXt"))
      }
      if (!is.null(`limit`)) {
        stopifnot(is.numeric(`limit`), length(`limit`) == 1)
      }
      if (!is.null(`offset`)) {
        stopifnot(is.numeric(`offset`), length(`offset`) == 1)
      }
      if (!is.null(`organization`)) {
        stopifnot(is.character(`organization`), length(`organization`) == 1)
      }
      if (!is.null(`projectIds`)) {
        stopifnot(is.vector(`projectIds`))
      }
      if (!is.null(`searchFor`)) {
        stopifnot(is.character(`searchFor`), length(`searchFor`) == 1)
      }
    }
  ),
  public = list(
    `creator` = NULL,
    `deletedAfter` = NULL,
    `deletedBefore` = NULL,
    `limit` = NULL,
    `offset` = NULL,
    `organization` = NULL,
    `projectIds` = NULL,
    `searchFor` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param creator Creator ID to filter projects by
    #' @param deletedAfter ISO-8601 formatted date projects were deleted after
    #' @param deletedBefore ISO-8601 formatted date projects were deleted before
    #' @param limit At most this many projects are deleted.
    #' @param offset This many projects will be skipped.
    #' @param organization ID of organization that projects should belong to
    #' @param projectIds List of project IDs to delete permanently.
    #' @param searchFor Project or dataset name to filter by
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`creator` = NULL, `deletedAfter` = NULL, `deletedBefore` = NULL, `limit` = 1000, `offset` = 0, `organization` = NULL, `projectIds` = NULL, `searchFor` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list()
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(creator, deletedAfter, deletedBefore, limit, offset, organization, projectIds, searchFor)
      }
      self$`creator` <- `creator`
      self$`deletedAfter` <- `deletedAfter`
      self$`deletedBefore` <- `deletedBefore`
      self$`limit` <- `limit`
      self$`offset` <- `offset`
      self$`organization` <- `organization`
      sapply(`projectIds`, function(x) stopifnot(is.character(x)))
      self$`searchFor` <- `searchFor`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(creator = self$`creator`, deletedAfter = self$`deletedAfter`, deletedBefore = self$`deletedBefore`, limit = self$`limit`, offset = self$`offset`, organization = self$`organization`, projectIds = self$`projectIds`, searchFor = self$`searchFor`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`creator`)) {
          sprintf(
            '"creator":
            "%s"
                  ',
            self$`creator`
          )
        },
        if (!is.null(self$`deletedAfter`)) {
          sprintf(
            '"deletedAfter":
            "%s"
                  ',
            format(self$`deletedAfter`, format = "%Y-%m-%dT%H:%M:%OSZ", tz = "UTC")
          )
        },
        if (!is.null(self$`deletedBefore`)) {
          sprintf(
            '"deletedBefore":
            "%s"
                  ',
            format(self$`deletedBefore`, format = "%Y-%m-%dT%H:%M:%OSZ", tz = "UTC")
          )
        },
        if (!is.null(self$`limit`)) {
          sprintf(
            '"limit":
            %d
                  ',
            self$`limit`
          )
        },
        if (!is.null(self$`offset`)) {
          sprintf(
            '"offset":
            %d
                  ',
            self$`offset`
          )
        },
        if (!is.null(self$`organization`)) {
          sprintf(
            '"organization":
            "%s"
                  ',
            self$`organization`
          )
        },
        if (!is.null(self$`projectIds`)) {
          sprintf(
            '"projectIds":
              [%s]
            ',
            paste(unlist(lapply(self$`projectIds`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`searchFor`)) {
          sprintf(
            '"searchFor":
            "%s"
                  ',
            self$`searchFor`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param ProjectNukeJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(ProjectNukeJson, validateParams = FALSE) {
      ProjectNukeObject <- jsonlite::fromJSON(ProjectNukeJson)
      self$`creator` <- ProjectNukeObject$`creator`
      self$`deletedAfter` <- ParseRFC3339Timestamp(ProjectNukeObject$`deletedAfter`)
      self$`deletedBefore` <- ParseRFC3339Timestamp(ProjectNukeObject$`deletedBefore`)
      self$`limit` <- ProjectNukeObject$`limit`
      self$`offset` <- ProjectNukeObject$`offset`
      self$`organization` <- ProjectNukeObject$`organization`
      self$`projectIds` <- ApiClient$new()$deserializeObj(ProjectNukeObject$`projectIds`, "array[character]", loadNamespace("datarobot.apicore"))
      self$`searchFor` <- ProjectNukeObject$`searchFor`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
