# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ProjectSegmentUpdateResponse
#'
#' @description ProjectSegmentUpdateResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field projectId  character New project id of the restarted segment
#'
#' @field segmentId  character The name of the restarted segment
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ProjectSegmentUpdateResponse <- R6::R6Class(
  "ProjectSegmentUpdateResponse",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`projectId` = NULL, `segmentId` = NULL) {
      if (!is.null(`projectId`)) {
        stopifnot(is.character(`projectId`), length(`projectId`) == 1)
      }
      if (!is.null(`segmentId`)) {
        stopifnot(is.character(`segmentId`), length(`segmentId`) == 1)
      }
    }
  ),
  public = list(
    `projectId` = NULL,
    `segmentId` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param projectId New project id of the restarted segment
    #' @param segmentId The name of the restarted segment
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`projectId` = NULL, `segmentId` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`projectId`, `segmentId`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(projectId, segmentId)
      }
      self$`projectId` <- `projectId`
      self$`segmentId` <- `segmentId`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(projectId = self$`projectId`, segmentId = self$`segmentId`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`projectId`)) {
          sprintf(
            '"projectId":
            "%s"
                  ',
            self$`projectId`
          )
        },
        if (!is.null(self$`segmentId`)) {
          sprintf(
            '"segmentId":
            "%s"
                  ',
            self$`segmentId`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param ProjectSegmentUpdateResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(ProjectSegmentUpdateResponseJson, validateParams = FALSE) {
      ProjectSegmentUpdateResponseObject <- jsonlite::fromJSON(ProjectSegmentUpdateResponseJson)
      self$`projectId` <- ProjectSegmentUpdateResponseObject$`projectId`
      self$`segmentId` <- ProjectSegmentUpdateResponseObject$`segmentId`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
