# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RatingTableCreateResponse
#'
#' @description RatingTableCreateResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field ratingTableId  character the ID of the newly created rating table
#'
#' @field ratingTableName  character The name that was used for the rating table. May differ from the ratingTableName in the request, as names are trimmed and a suffix added to ensure all rating tables derived from the same model have unique names
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RatingTableCreateResponse <- R6::R6Class(
  "RatingTableCreateResponse",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`ratingTableId` = NULL, `ratingTableName` = NULL) {
      if (!is.null(`ratingTableId`)) {
        stopifnot(is.character(`ratingTableId`), length(`ratingTableId`) == 1)
      }
      if (!is.null(`ratingTableName`)) {
        stopifnot(is.character(`ratingTableName`), length(`ratingTableName`) == 1)
      }
    }
  ),
  public = list(
    `ratingTableId` = NULL,
    `ratingTableName` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param ratingTableId the ID of the newly created rating table
    #' @param ratingTableName The name that was used for the rating table. May differ from the ratingTableName in the request, as names are trimmed and a suffix added to ensure all rating tables derived from the same model have unique names
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`ratingTableId` = NULL, `ratingTableName` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`ratingTableId`, `ratingTableName`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(ratingTableId, ratingTableName)
      }
      self$`ratingTableId` <- `ratingTableId`
      self$`ratingTableName` <- `ratingTableName`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(ratingTableId = self$`ratingTableId`, ratingTableName = self$`ratingTableName`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`ratingTableId`)) {
          sprintf(
            '"ratingTableId":
            "%s"
                  ',
            self$`ratingTableId`
          )
        },
        if (!is.null(self$`ratingTableName`)) {
          sprintf(
            '"ratingTableName":
            "%s"
                  ',
            self$`ratingTableName`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param RatingTableCreateResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(RatingTableCreateResponseJson, validateParams = FALSE) {
      RatingTableCreateResponseObject <- jsonlite::fromJSON(RatingTableCreateResponseJson)
      self$`ratingTableId` <- RatingTableCreateResponseObject$`ratingTableId`
      self$`ratingTableName` <- RatingTableCreateResponseObject$`ratingTableName`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
