# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ScheduledJobsListResponse
#'
#' @description ScheduledJobsListResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field count  integer [optional] Number of items returned on this page.
#'
#' @field data  list( \link{ScheduledJobResponse} ) List of scheduled jobs
#'
#' @field next_  character URL pointing to the next page (if null, there is no next page).
#'
#' @field previous  character URL pointing to the previous page (if null, there is no previous page).
#'
#' @field totalCount  integer The total number of items across all pages.
#'
#' @field updatedAt  character [optional] Time of last modification
#'
#' @field updatedBy  character [optional] User ID of last modifier
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ScheduledJobsListResponse <- R6::R6Class(
  "ScheduledJobsListResponse",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(count = NULL, data = NULL, next_ = NULL, previous = NULL, totalCount = NULL, updatedAt = NULL, updatedBy = NULL) {
      if (!is.null(`data`)) {
        stopifnot(is.vector(`data`))
      }
      if (!is.null(`next_`)) {
        stopifnot(is.character(`next_`), length(`next_`) == 1)
      }
      if (!is.null(`previous`)) {
        stopifnot(is.character(`previous`), length(`previous`) == 1)
      }
      if (!is.null(`totalCount`)) {
        stopifnot(is.numeric(`totalCount`), length(`totalCount`) == 1)
      }
      if (!is.null(`count`)) {
        stopifnot(is.numeric(`count`), length(`count`) == 1)
      }
      if (!is.null(`updatedAt`)) {
        stopifnot(inherits(`updatedAt`, "POSIXt"))
      }
      if (!is.null(`updatedBy`)) {
        stopifnot(is.character(`updatedBy`), length(`updatedBy`) == 1)
      }
    }
  ),
  public = list(
    `count` = NULL,
    `data` = NULL,
    `next_` = NULL,
    `previous` = NULL,
    `totalCount` = NULL,
    `updatedAt` = NULL,
    `updatedBy` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param count Number of items returned on this page.
    #' @param data List of scheduled jobs
    #' @param next_ URL pointing to the next page (if null, there is no next page).
    #' @param previous URL pointing to the previous page (if null, there is no previous page).
    #' @param totalCount The total number of items across all pages.
    #' @param updatedAt Time of last modification
    #' @param updatedBy User ID of last modifier
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`data` = NULL, `next_` = NULL, `previous` = NULL, `totalCount` = NULL, `count` = NULL, `updatedAt` = NULL, `updatedBy` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`data`, `next_`, `previous`, `totalCount`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(count, data, next_, previous, totalCount, updatedAt, updatedBy)
      }
      self$`count` <- `count`
      sapply(`data`, function(x) stopifnot(R6::is.R6(x)))
      self$`next_` <- `next_`
      self$`previous` <- `previous`
      self$`totalCount` <- `totalCount`
      self$`updatedAt` <- `updatedAt`
      self$`updatedBy` <- `updatedBy`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(count = self$`count`, data = self$`data`, next_ = self$`next_`, previous = self$`previous`, totalCount = self$`totalCount`, updatedAt = self$`updatedAt`, updatedBy = self$`updatedBy`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`count`)) {
          sprintf(
            '"count":
            %d
                  ',
            self$`count`
          )
        },
        if (!is.null(self$`data`)) {
          sprintf(
            '"data":
            [%s]
',
            paste(sapply(self$`data`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`next_`)) {
          sprintf(
            '"next":
            "%s"
                  ',
            self$`next_`
          )
        },
        if (!is.null(self$`previous`)) {
          sprintf(
            '"previous":
            "%s"
                  ',
            self$`previous`
          )
        },
        if (!is.null(self$`totalCount`)) {
          sprintf(
            '"totalCount":
            %d
                  ',
            self$`totalCount`
          )
        },
        if (!is.null(self$`updatedAt`)) {
          sprintf(
            '"updatedAt":
            "%s"
                  ',
            format(self$`updatedAt`, format = "%Y-%m-%dT%H:%M:%OSZ", tz = "UTC")
          )
        },
        if (!is.null(self$`updatedBy`)) {
          sprintf(
            '"updatedBy":
            "%s"
                  ',
            self$`updatedBy`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param ScheduledJobsListResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(ScheduledJobsListResponseJson, validateParams = FALSE) {
      ScheduledJobsListResponseObject <- jsonlite::fromJSON(ScheduledJobsListResponseJson)
      self$`count` <- ScheduledJobsListResponseObject$`count`
      self$`data` <- ApiClient$new()$deserializeObj(ScheduledJobsListResponseObject$`data`, "array[ScheduledJobResponse]", loadNamespace("datarobot.apicore"))
      self$`next_` <- ScheduledJobsListResponseObject$`next`
      self$`previous` <- ScheduledJobsListResponseObject$`previous`
      self$`totalCount` <- ScheduledJobsListResponseObject$`totalCount`
      self$`updatedAt` <- ParseRFC3339Timestamp(ScheduledJobsListResponseObject$`updatedAt`)
      self$`updatedBy` <- ScheduledJobsListResponseObject$`updatedBy`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
