# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StageCoefficients
#'
#' @description StageCoefficients Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field coefficient  numeric The corresponding value of the coefficient for that stage.
#'
#' @field stage  character The name of the stage.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StageCoefficients <- R6::R6Class(
  "StageCoefficients",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`coefficient` = NULL, `stage` = NULL) {
      if (!is.null(`coefficient`)) {
      }
      if (!is.null(`stage`)) {
        stopifnot(is.character(`stage`), length(`stage`) == 1)
      }
    }
  ),
  public = list(
    `coefficient` = NULL,
    `stage` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param coefficient The corresponding value of the coefficient for that stage.
    #' @param stage The name of the stage.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`coefficient` = NULL, `stage` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`coefficient`, `stage`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(coefficient, stage)
      }
      self$`coefficient` <- `coefficient`
      self$`stage` <- `stage`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(coefficient = self$`coefficient`, stage = self$`stage`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`coefficient`)) {
          sprintf(
            '"coefficient":
            %d
                  ',
            self$`coefficient`
          )
        },
        if (!is.null(self$`stage`)) {
          sprintf(
            '"stage":
            "%s"
                  ',
            self$`stage`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param StageCoefficientsJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(StageCoefficientsJson, validateParams = FALSE) {
      StageCoefficientsObject <- jsonlite::fromJSON(StageCoefficientsJson)
      self$`coefficient` <- StageCoefficientsObject$`coefficient`
      self$`stage` <- StageCoefficientsObject$`stage`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
