# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SynapseOutput
#'
#' @description SynapseOutput Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field cloudStorageCredentialId  character [optional] The ID of the credential holding information about a user with write access to the cloud storage.
#'
#' @field createTableIfNotExists  character [optional] Attempt to create the table first if no existing one is detected, before writing data with the strategy defined in the &#x60;statementType&#x60; parameter.
#'
#' @field credentialId  character [optional] The ID of the credential holding information about a user with write access to the JDBC data source.
#'
#' @field dataStoreId  character ID of the data store to connect to
#'
#' @field externalDataSource  character External data source name
#'
#' @field schema  character [optional] The name of the specified database schema to write results to.
#'
#' @field statementType  character The statement type to use when writing the results.
#'
#' @field table  character The name of the specified database table to write results to.
#'
#' @field type  character Type name for this output type
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SynapseOutput <- R6::R6Class(
  "SynapseOutput",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(cloudStorageCredentialId = NULL, createTableIfNotExists = NULL, credentialId = NULL, dataStoreId = NULL, externalDataSource = NULL, schema = NULL, statementType = NULL, table = NULL, type = NULL) {
      if (!is.null(`dataStoreId`)) {
        stopifnot(is.character(`dataStoreId`), length(`dataStoreId`) == 1)
      }
      if (!is.null(`externalDataSource`)) {
        stopifnot(is.character(`externalDataSource`), length(`externalDataSource`) == 1)
      }
      if (!is.null(`statementType`)) {
        stopifnot(is.character(`statementType`), length(`statementType`) == 1)
      }
      if (!is.null(`table`)) {
        stopifnot(is.character(`table`), length(`table`) == 1)
      }
      if (!is.null(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
      }
      if (!is.null(`cloudStorageCredentialId`)) {
        stopifnot(is.character(`cloudStorageCredentialId`), length(`cloudStorageCredentialId`) == 1)
      }
      if (!is.null(`createTableIfNotExists`)) {
        stopifnot(is.logical(`createTableIfNotExists`), length(`createTableIfNotExists`) == 1)
      }
      if (!is.null(`credentialId`)) {
        stopifnot(is.character(`credentialId`), length(`credentialId`) == 1)
      }
      if (!is.null(`schema`)) {
        stopifnot(is.character(`schema`), length(`schema`) == 1)
      }
    }
  ),
  public = list(
    `cloudStorageCredentialId` = NULL,
    `createTableIfNotExists` = NULL,
    `credentialId` = NULL,
    `dataStoreId` = NULL,
    `externalDataSource` = NULL,
    `schema` = NULL,
    `statementType` = NULL,
    `table` = NULL,
    `type` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param cloudStorageCredentialId The ID of the credential holding information about a user with write access to the cloud storage.
    #' @param createTableIfNotExists Attempt to create the table first if no existing one is detected, before writing data with the strategy defined in the &#x60;statementType&#x60; parameter.
    #' @param credentialId The ID of the credential holding information about a user with write access to the JDBC data source.
    #' @param dataStoreId ID of the data store to connect to
    #' @param externalDataSource External data source name
    #' @param schema The name of the specified database schema to write results to.
    #' @param statementType The statement type to use when writing the results.
    #' @param table The name of the specified database table to write results to.
    #' @param type Type name for this output type
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`dataStoreId` = NULL, `externalDataSource` = NULL, `statementType` = NULL, `table` = NULL, `type` = NULL, `cloudStorageCredentialId` = NULL, `createTableIfNotExists` = FALSE, `credentialId` = NULL, `schema` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`dataStoreId`, `externalDataSource`, `statementType`, `table`, `type`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(cloudStorageCredentialId, createTableIfNotExists, credentialId, dataStoreId, externalDataSource, schema, statementType, table, type)
      }
      self$`cloudStorageCredentialId` <- `cloudStorageCredentialId`
      self$`createTableIfNotExists` <- `createTableIfNotExists`
      self$`credentialId` <- `credentialId`
      self$`dataStoreId` <- `dataStoreId`
      self$`externalDataSource` <- `externalDataSource`
      self$`schema` <- `schema`
      self$`statementType` <- `statementType`
      self$`table` <- `table`
      self$`type` <- `type`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(cloudStorageCredentialId = self$`cloudStorageCredentialId`, createTableIfNotExists = self$`createTableIfNotExists`, credentialId = self$`credentialId`, dataStoreId = self$`dataStoreId`, externalDataSource = self$`externalDataSource`, schema = self$`schema`, statementType = self$`statementType`, table = self$`table`, type = self$`type`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`cloudStorageCredentialId`)) {
          sprintf(
            '"cloudStorageCredentialId":
            "%s"
                  ',
            self$`cloudStorageCredentialId`
          )
        },
        if (!is.null(self$`createTableIfNotExists`)) {
          sprintf(
            '"createTableIfNotExists":
            %s
                  ',
            tolower(self$`createTableIfNotExists`)
          )
        },
        if (!is.null(self$`credentialId`)) {
          sprintf(
            '"credentialId":
            "%s"
                  ',
            self$`credentialId`
          )
        },
        if (!is.null(self$`dataStoreId`)) {
          sprintf(
            '"dataStoreId":
            "%s"
                  ',
            self$`dataStoreId`
          )
        },
        if (!is.null(self$`externalDataSource`)) {
          sprintf(
            '"externalDataSource":
            "%s"
                  ',
            self$`externalDataSource`
          )
        },
        if (!is.null(self$`schema`)) {
          sprintf(
            '"schema":
            "%s"
                  ',
            self$`schema`
          )
        },
        if (!is.null(self$`statementType`)) {
          sprintf(
            '"statementType":
            "%s"
                  ',
            self$`statementType`
          )
        },
        if (!is.null(self$`table`)) {
          sprintf(
            '"table":
            "%s"
                  ',
            self$`table`
          )
        },
        if (!is.null(self$`type`)) {
          sprintf(
            '"type":
            "%s"
                  ',
            self$`type`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param SynapseOutputJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(SynapseOutputJson, validateParams = FALSE) {
      SynapseOutputObject <- jsonlite::fromJSON(SynapseOutputJson)
      self$`cloudStorageCredentialId` <- SynapseOutputObject$`cloudStorageCredentialId`
      self$`createTableIfNotExists` <- SynapseOutputObject$`createTableIfNotExists`
      self$`credentialId` <- SynapseOutputObject$`credentialId`
      self$`dataStoreId` <- SynapseOutputObject$`dataStoreId`
      self$`externalDataSource` <- SynapseOutputObject$`externalDataSource`
      self$`schema` <- SynapseOutputObject$`schema`
      self$`statementType` <- SynapseOutputObject$`statementType`
      self$`table` <- SynapseOutputObject$`table`
      self$`type` <- SynapseOutputObject$`type`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
