# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Tableau
#'
#' @description Tableau Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field contentUrl  character [optional] Deprecated, use &#x60;siteName&#x60; instead
#'
#' @field credentialId  character [optional] Use the specified credential to access the url
#'
#' @field dataSourceId  character The ID of your Tableau data source
#'
#' @field overwrite  character Should the dataset be overwritten or appended to
#'
#' @field siteName  character [optional] Your Tableau site name
#'
#' @field type  character Type name for this output type
#'
#' @field url  character The URL to your online Tableau server
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Tableau <- R6::R6Class(
  "Tableau",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`contentUrl` = NULL, `credentialId` = NULL, `dataSourceId` = NULL, `overwrite` = NULL, `siteName` = NULL, `type` = NULL, `url` = NULL) {
      if (!is.null(`dataSourceId`)) {
        stopifnot(is.character(`dataSourceId`), length(`dataSourceId`) == 1)
      }
      if (!is.null(`overwrite`)) {
        stopifnot(is.logical(`overwrite`), length(`overwrite`) == 1)
      }
      if (!is.null(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
      }
      if (!is.null(`url`)) {
        stopifnot(is.character(`url`), length(`url`) == 1)
      }
      if (!is.null(`contentUrl`)) {
        stopifnot(is.character(`contentUrl`), length(`contentUrl`) == 1)
      }
      if (!is.null(`credentialId`)) {
        stopifnot(is.character(`credentialId`), length(`credentialId`) == 1)
      }
      if (!is.null(`siteName`)) {
        stopifnot(is.character(`siteName`), length(`siteName`) == 1)
      }
    }
  ),
  public = list(
    `contentUrl` = NULL,
    `credentialId` = NULL,
    `dataSourceId` = NULL,
    `overwrite` = NULL,
    `siteName` = NULL,
    `type` = NULL,
    `url` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param contentUrl Deprecated, use &#x60;siteName&#x60; instead
    #' @param credentialId Use the specified credential to access the url
    #' @param dataSourceId The ID of your Tableau data source
    #' @param overwrite Should the dataset be overwritten or appended to
    #' @param siteName Your Tableau site name
    #' @param type Type name for this output type
    #' @param url The URL to your online Tableau server
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`dataSourceId` = NULL, `overwrite` = NULL, `type` = NULL, `url` = NULL, `contentUrl` = NULL, `credentialId` = NULL, `siteName` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`dataSourceId`, `overwrite`, `type`, `url`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(contentUrl, credentialId, dataSourceId, overwrite, siteName, type, url)
      }
      self$`contentUrl` <- `contentUrl`
      self$`credentialId` <- `credentialId`
      self$`dataSourceId` <- `dataSourceId`
      self$`overwrite` <- `overwrite`
      self$`siteName` <- `siteName`
      self$`type` <- `type`
      self$`url` <- `url`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(contentUrl = self$`contentUrl`, credentialId = self$`credentialId`, dataSourceId = self$`dataSourceId`, overwrite = self$`overwrite`, siteName = self$`siteName`, type = self$`type`, url = self$`url`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`contentUrl`)) {
          sprintf(
            '"contentUrl":
            "%s"
                  ',
            self$`contentUrl`
          )
        },
        if (!is.null(self$`credentialId`)) {
          sprintf(
            '"credentialId":
            "%s"
                  ',
            self$`credentialId`
          )
        },
        if (!is.null(self$`dataSourceId`)) {
          sprintf(
            '"dataSourceId":
            "%s"
                  ',
            self$`dataSourceId`
          )
        },
        if (!is.null(self$`overwrite`)) {
          sprintf(
            '"overwrite":
            %s
                  ',
            tolower(self$`overwrite`)
          )
        },
        if (!is.null(self$`siteName`)) {
          sprintf(
            '"siteName":
            "%s"
                  ',
            self$`siteName`
          )
        },
        if (!is.null(self$`type`)) {
          sprintf(
            '"type":
            "%s"
                  ',
            self$`type`
          )
        },
        if (!is.null(self$`url`)) {
          sprintf(
            '"url":
            "%s"
                  ',
            self$`url`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param TableauJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(TableauJson, validateParams = FALSE) {
      TableauObject <- jsonlite::fromJSON(TableauJson)
      self$`contentUrl` <- TableauObject$`contentUrl`
      self$`credentialId` <- TableauObject$`credentialId`
      self$`dataSourceId` <- TableauObject$`dataSourceId`
      self$`overwrite` <- TableauObject$`overwrite`
      self$`siteName` <- TableauObject$`siteName`
      self$`type` <- TableauObject$`type`
      self$`url` <- TableauObject$`url`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
