# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TextFeature
#'
#' @description TextFeature Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field featureImpact  numeric [optional] Feature Impact score.
#'
#' @field featureName  character Feature name.
#'
#' @field featureType  character Feature Type.
#'
#' @field insights  list( \link{Text} ) A list of Cluster Insights for a feature.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TextFeature <- R6::R6Class(
  "TextFeature",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(featureImpact = NULL, featureName = NULL, featureType = NULL, insights = NULL) {
      if (!is.null(`featureName`)) {
        stopifnot(is.character(`featureName`), length(`featureName`) == 1)
      }
      if (!is.null(`featureType`)) {
        stopifnot(is.character(`featureType`), length(`featureType`) == 1)
      }
      if (!is.null(`insights`)) {
        stopifnot(is.vector(`insights`))
      }
      if (!is.null(`featureImpact`)) {
        stopifnot(is.numeric(`featureImpact`), length(`featureImpact`) == 1)
      }
    }
  ),
  public = list(
    `featureImpact` = NULL,
    `featureName` = NULL,
    `featureType` = NULL,
    `insights` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param featureImpact Feature Impact score.
    #' @param featureName Feature name.
    #' @param featureType Feature Type.
    #' @param insights A list of Cluster Insights for a feature.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`featureName` = NULL, `featureType` = NULL, `insights` = NULL, `featureImpact` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`featureName`, `featureType`, `insights`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(featureImpact, featureName, featureType, insights)
      }
      self$`featureImpact` <- `featureImpact`
      self$`featureName` <- `featureName`
      self$`featureType` <- `featureType`
      sapply(`insights`, function(x) stopifnot(R6::is.R6(x)))
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(featureImpact = self$`featureImpact`, featureName = self$`featureName`, featureType = self$`featureType`, insights = self$`insights`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`featureImpact`)) {
          sprintf(
            '"featureImpact":
            %d
                  ',
            self$`featureImpact`
          )
        },
        if (!is.null(self$`featureName`)) {
          sprintf(
            '"featureName":
            "%s"
                  ',
            self$`featureName`
          )
        },
        if (!is.null(self$`featureType`)) {
          sprintf(
            '"featureType":
            "%s"
                  ',
            self$`featureType`
          )
        },
        if (!is.null(self$`insights`)) {
          sprintf(
            '"insights":
            [%s]
',
            paste(sapply(self$`insights`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param TextFeatureJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(TextFeatureJson, validateParams = FALSE) {
      TextFeatureObject <- jsonlite::fromJSON(TextFeatureJson)
      self$`featureImpact` <- TextFeatureObject$`featureImpact`
      self$`featureName` <- TextFeatureObject$`featureName`
      self$`featureType` <- TextFeatureObject$`featureType`
      self$`insights` <- ApiClient$new()$deserializeObj(TextFeatureObject$`insights`, "array[Text]", loadNamespace("datarobot.apicore"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
