# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TuningParameter
#'
#' @description TuningParameter Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field parameterId  character ID of the parameter whose value to set.
#'
#' @field value  \link{OneOfAnyTypearray} Value for the specified parameter.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TuningParameter <- R6::R6Class(
  "TuningParameter",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(parameterId = NULL, value = NULL) {
      if (!is.null(`parameterId`)) {
        stopifnot(is.character(`parameterId`), length(`parameterId`) == 1)
      }
      if (!is.null(`value`)) {
        .setMixedProperty(typeList = list(AnyType, array), propertyData = value)
      }
    }
  ),
  public = list(
    `parameterId` = NULL,
    `value` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param parameterId ID of the parameter whose value to set.
    #' @param value Value for the specified parameter.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`parameterId` = NULL, `value` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`parameterId`, `value`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(parameterId, value)
      }
      self$`parameterId` <- `parameterId`
      self$`value` <- `value`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(parameterId = self$`parameterId`, value = self$`value`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`parameterId`)) {
          sprintf(
            '"parameterId":
            "%s"
                  ',
            self$`parameterId`
          )
        },
        if (!is.null(self$`value`)) {
          sprintf(
            '"value":
          %s
        ',
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param TuningParameterJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(TuningParameterJson, validateParams = FALSE) {
      TuningParameterObject <- jsonlite::fromJSON(TuningParameterJson)
      self$`parameterId` <- TuningParameterObject$`parameterId`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
