# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UseCaseAttachmentModelPackageOverview
#'
#' @description UseCaseAttachmentModelPackageOverview Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field createdAt  character Time when model package was created
#'
#' @field deploymentCount  integer Number of deployments
#'
#' @field executionType  character Type of execution
#'
#' @field name  character Name of the model package
#'
#' @field targetName  character Name of modeling target
#'
#' @field targetType  character Type of modeling target
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UseCaseAttachmentModelPackageOverview <- R6::R6Class(
  "UseCaseAttachmentModelPackageOverview",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`createdAt` = NULL, `deploymentCount` = NULL, `executionType` = NULL, `name` = NULL, `targetName` = NULL, `targetType` = NULL) {
      if (!is.null(`createdAt`)) {
        stopifnot(inherits(`createdAt`, "POSIXt"))
      }
      if (!is.null(`deploymentCount`)) {
        stopifnot(is.numeric(`deploymentCount`), length(`deploymentCount`) == 1)
      }
      if (!is.null(`executionType`)) {
        stopifnot(is.character(`executionType`), length(`executionType`) == 1)
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
      }
      if (!is.null(`targetName`)) {
        stopifnot(is.character(`targetName`), length(`targetName`) == 1)
      }
      if (!is.null(`targetType`)) {
        stopifnot(is.character(`targetType`), length(`targetType`) == 1)
      }
    }
  ),
  public = list(
    `createdAt` = NULL,
    `deploymentCount` = NULL,
    `executionType` = NULL,
    `name` = NULL,
    `targetName` = NULL,
    `targetType` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param createdAt Time when model package was created
    #' @param deploymentCount Number of deployments
    #' @param executionType Type of execution
    #' @param name Name of the model package
    #' @param targetName Name of modeling target
    #' @param targetType Type of modeling target
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`createdAt` = NULL, `deploymentCount` = NULL, `executionType` = NULL, `name` = NULL, `targetName` = NULL, `targetType` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`createdAt`, `deploymentCount`, `executionType`, `name`, `targetName`, `targetType`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(createdAt, deploymentCount, executionType, name, targetName, targetType)
      }
      self$`createdAt` <- `createdAt`
      self$`deploymentCount` <- `deploymentCount`
      self$`executionType` <- `executionType`
      self$`name` <- `name`
      self$`targetName` <- `targetName`
      self$`targetType` <- `targetType`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(createdAt = self$`createdAt`, deploymentCount = self$`deploymentCount`, executionType = self$`executionType`, name = self$`name`, targetName = self$`targetName`, targetType = self$`targetType`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`createdAt`)) {
          sprintf(
            '"createdAt":
            "%s"
                  ',
            format(self$`createdAt`, format = "%Y-%m-%dT%H:%M:%OSZ", tz = "UTC")
          )
        },
        if (!is.null(self$`deploymentCount`)) {
          sprintf(
            '"deploymentCount":
            %d
                  ',
            self$`deploymentCount`
          )
        },
        if (!is.null(self$`executionType`)) {
          sprintf(
            '"executionType":
            "%s"
                  ',
            self$`executionType`
          )
        },
        if (!is.null(self$`name`)) {
          sprintf(
            '"name":
            "%s"
                  ',
            self$`name`
          )
        },
        if (!is.null(self$`targetName`)) {
          sprintf(
            '"targetName":
            "%s"
                  ',
            self$`targetName`
          )
        },
        if (!is.null(self$`targetType`)) {
          sprintf(
            '"targetType":
            "%s"
                  ',
            self$`targetType`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param UseCaseAttachmentModelPackageOverviewJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(UseCaseAttachmentModelPackageOverviewJson, validateParams = FALSE) {
      UseCaseAttachmentModelPackageOverviewObject <- jsonlite::fromJSON(UseCaseAttachmentModelPackageOverviewJson)
      self$`createdAt` <- ParseRFC3339Timestamp(UseCaseAttachmentModelPackageOverviewObject$`createdAt`)
      self$`deploymentCount` <- UseCaseAttachmentModelPackageOverviewObject$`deploymentCount`
      self$`executionType` <- UseCaseAttachmentModelPackageOverviewObject$`executionType`
      self$`name` <- UseCaseAttachmentModelPackageOverviewObject$`name`
      self$`targetName` <- UseCaseAttachmentModelPackageOverviewObject$`targetName`
      self$`targetType` <- UseCaseAttachmentModelPackageOverviewObject$`targetType`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
