# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UseCaseValueTemplateSchema
#'
#' @description UseCaseValueTemplateSchema Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field elementType  character Possible types used for template variables
#'
#' @field label  character Label describing the represented value
#'
#' @field maximum  integer Sets Maximum value if given
#'
#' @field minimum  integer Sets Minimum value if given
#'
#' @field placeholder  character Text that can be used to prefill an input filed for the value
#'
#' @field unit  character Unit type. e.g. %
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UseCaseValueTemplateSchema <- R6::R6Class(
  "UseCaseValueTemplateSchema",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`elementType` = NULL, `label` = NULL, `maximum` = NULL, `minimum` = NULL, `placeholder` = NULL, `unit` = NULL) {
      if (!is.null(`elementType`)) {
        stopifnot(is.character(`elementType`), length(`elementType`) == 1)
      }
      if (!is.null(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
      }
      if (!is.null(`maximum`)) {
        stopifnot(is.numeric(`maximum`), length(`maximum`) == 1)
      }
      if (!is.null(`minimum`)) {
        stopifnot(is.numeric(`minimum`), length(`minimum`) == 1)
      }
      if (!is.null(`placeholder`)) {
        stopifnot(is.character(`placeholder`), length(`placeholder`) == 1)
      }
      if (!is.null(`unit`)) {
        stopifnot(is.character(`unit`), length(`unit`) == 1)
      }
    }
  ),
  public = list(
    `elementType` = NULL,
    `label` = NULL,
    `maximum` = NULL,
    `minimum` = NULL,
    `placeholder` = NULL,
    `unit` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param elementType Possible types used for template variables
    #' @param label Label describing the represented value
    #' @param maximum Sets Maximum value if given
    #' @param minimum Sets Minimum value if given
    #' @param placeholder Text that can be used to prefill an input filed for the value
    #' @param unit Unit type. e.g. %
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`elementType` = NULL, `label` = NULL, `maximum` = NULL, `minimum` = NULL, `placeholder` = NULL, `unit` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`elementType`, `label`, `maximum`, `minimum`, `placeholder`, `unit`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(elementType, label, maximum, minimum, placeholder, unit)
      }
      self$`elementType` <- `elementType`
      self$`label` <- `label`
      self$`maximum` <- `maximum`
      self$`minimum` <- `minimum`
      self$`placeholder` <- `placeholder`
      self$`unit` <- `unit`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(elementType = self$`elementType`, label = self$`label`, maximum = self$`maximum`, minimum = self$`minimum`, placeholder = self$`placeholder`, unit = self$`unit`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`elementType`)) {
          sprintf(
            '"elementType":
            "%s"
                  ',
            self$`elementType`
          )
        },
        if (!is.null(self$`label`)) {
          sprintf(
            '"label":
            "%s"
                  ',
            self$`label`
          )
        },
        if (!is.null(self$`maximum`)) {
          sprintf(
            '"maximum":
            %d
                  ',
            self$`maximum`
          )
        },
        if (!is.null(self$`minimum`)) {
          sprintf(
            '"minimum":
            %d
                  ',
            self$`minimum`
          )
        },
        if (!is.null(self$`placeholder`)) {
          sprintf(
            '"placeholder":
            "%s"
                  ',
            self$`placeholder`
          )
        },
        if (!is.null(self$`unit`)) {
          sprintf(
            '"unit":
            "%s"
                  ',
            self$`unit`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param UseCaseValueTemplateSchemaJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(UseCaseValueTemplateSchemaJson, validateParams = FALSE) {
      UseCaseValueTemplateSchemaObject <- jsonlite::fromJSON(UseCaseValueTemplateSchemaJson)
      self$`elementType` <- UseCaseValueTemplateSchemaObject$`elementType`
      self$`label` <- UseCaseValueTemplateSchemaObject$`label`
      self$`maximum` <- UseCaseValueTemplateSchemaObject$`maximum`
      self$`minimum` <- UseCaseValueTemplateSchemaObject$`minimum`
      self$`placeholder` <- UseCaseValueTemplateSchemaObject$`placeholder`
      self$`unit` <- UseCaseValueTemplateSchemaObject$`unit`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
