# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UseCaseRealizedValuesOverTimeResponse
#'
#' @description UseCaseRealizedValuesOverTimeResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field buckets  list( \link{UseCaseBucket} ) An array of &#x60;bucket&#x60; objects representing prediction totals and realized value over time
#'
#' @field previousTimeRangeSummary  \link{UseCaseSummary}
#'
#' @field summary  \link{UseCaseSummary}
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UseCaseRealizedValuesOverTimeResponse <- R6::R6Class(
  "UseCaseRealizedValuesOverTimeResponse",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(buckets = NULL, previousTimeRangeSummary = NULL, summary = NULL) {
      if (!is.null(`buckets`)) {
        stopifnot(is.vector(`buckets`))
      }
      if (!is.null(`previousTimeRangeSummary`)) {
        stopifnot(R6::is.R6(`previousTimeRangeSummary`))
      }
      if (!is.null(`summary`)) {
        stopifnot(R6::is.R6(`summary`))
      }
    }
  ),
  public = list(
    `buckets` = NULL,
    `previousTimeRangeSummary` = NULL,
    `summary` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param buckets An array of &#x60;bucket&#x60; objects representing prediction totals and realized value over time
    #' @param previousTimeRangeSummary
    #' @param summary
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`buckets` = NULL, `previousTimeRangeSummary` = NULL, `summary` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`buckets`, `previousTimeRangeSummary`, `summary`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(buckets, previousTimeRangeSummary, summary)
      }
      sapply(`buckets`, function(x) stopifnot(R6::is.R6(x)))
      self$`previousTimeRangeSummary` <- `previousTimeRangeSummary`
      self$`summary` <- `summary`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(buckets = self$`buckets`, previousTimeRangeSummary = self$`previousTimeRangeSummary`, summary = self$`summary`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`buckets`)) {
          sprintf(
            '"buckets":
            [%s]
',
            paste(sapply(self$`buckets`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`previousTimeRangeSummary`)) {
          sprintf(
            '"previousTimeRangeSummary":
          %s
        ',
            jsonlite::toJSON(self$`previousTimeRangeSummary`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        },
        if (!is.null(self$`summary`)) {
          sprintf(
            '"summary":
          %s
        ',
            jsonlite::toJSON(self$`summary`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param UseCaseRealizedValuesOverTimeResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(UseCaseRealizedValuesOverTimeResponseJson, validateParams = FALSE) {
      UseCaseRealizedValuesOverTimeResponseObject <- jsonlite::fromJSON(UseCaseRealizedValuesOverTimeResponseJson)
      self$`buckets` <- ApiClient$new()$deserializeObj(UseCaseRealizedValuesOverTimeResponseObject$`buckets`, "array[UseCaseBucket]", loadNamespace("datarobot.apicore"))
      self$`previousTimeRangeSummary` <- UseCaseSummary$new()$fromJSON(jsonlite::toJSON(UseCaseRealizedValuesOverTimeResponseObject$previousTimeRangeSummary, auto_unbox = TRUE, digits = NA, null = "null"))
      self$`summary` <- UseCaseSummary$new()$fromJSON(jsonlite::toJSON(UseCaseRealizedValuesOverTimeResponseObject$summary, auto_unbox = TRUE, digits = NA, null = "null"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
