# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UserNotificationRelatedUsersDeleteResponse
#'
#' @description UserNotificationRelatedUsersDeleteResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field reportId  character The ID of the users permanent delete report
#'
#' @field statusId  character The ID of the users delete status.
#'
#' @field usersToDeleteCount  character Number of users that will be deleted.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserNotificationRelatedUsersDeleteResponse <- R6::R6Class(
  "UserNotificationRelatedUsersDeleteResponse",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`reportId` = NULL, `statusId` = NULL, `usersToDeleteCount` = NULL) {
      if (!is.null(`reportId`)) {
        stopifnot(is.character(`reportId`), length(`reportId`) == 1)
      }
      if (!is.null(`statusId`)) {
        stopifnot(is.character(`statusId`), length(`statusId`) == 1)
      }
      if (!is.null(`usersToDeleteCount`)) {
        stopifnot(is.character(`usersToDeleteCount`), length(`usersToDeleteCount`) == 1)
      }
    }
  ),
  public = list(
    `reportId` = NULL,
    `statusId` = NULL,
    `usersToDeleteCount` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param reportId The ID of the users permanent delete report
    #' @param statusId The ID of the users delete status.
    #' @param usersToDeleteCount Number of users that will be deleted.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`reportId` = NULL, `statusId` = NULL, `usersToDeleteCount` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(`reportId`, `statusId`, `usersToDeleteCount`), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(reportId, statusId, usersToDeleteCount)
      }
      self$`reportId` <- `reportId`
      self$`statusId` <- `statusId`
      self$`usersToDeleteCount` <- `usersToDeleteCount`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(reportId = self$`reportId`, statusId = self$`statusId`, usersToDeleteCount = self$`usersToDeleteCount`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`reportId`)) {
          sprintf(
            '"reportId":
            "%s"
                  ',
            self$`reportId`
          )
        },
        if (!is.null(self$`statusId`)) {
          sprintf(
            '"statusId":
            "%s"
                  ',
            self$`statusId`
          )
        },
        if (!is.null(self$`usersToDeleteCount`)) {
          sprintf(
            '"usersToDeleteCount":
            "%s"
                  ',
            self$`usersToDeleteCount`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param UserNotificationRelatedUsersDeleteResponseJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(UserNotificationRelatedUsersDeleteResponseJson, validateParams = FALSE) {
      UserNotificationRelatedUsersDeleteResponseObject <- jsonlite::fromJSON(UserNotificationRelatedUsersDeleteResponseJson)
      self$`reportId` <- UserNotificationRelatedUsersDeleteResponseObject$`reportId`
      self$`statusId` <- UserNotificationRelatedUsersDeleteResponseObject$`statusId`
      self$`usersToDeleteCount` <- UserNotificationRelatedUsersDeleteResponseObject$`usersToDeleteCount`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
