# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UsersPermadeletePreviewStatistics
#'
#' @description UsersPermadeletePreviewStatistics Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field deploymentsWillBeAssignedNewOwner  integer Number of deployments that will be assigned a new owner.
#'
#' @field deploymentsWillBeDeleted  integer Number of deployments that will be deleted.
#'
#' @field deploymentsWillNotBeDeleted  integer Number of deployments that will not be deleted.
#'
#' @field errors  integer Number of errors encountered during preview construction.
#'
#' @field projectsWillBeAssignedNewOwner  integer Number of projects that will be assigned a new owner.
#'
#' @field projectsWillBeDeleted  integer Number of projects that will be deleted.
#'
#' @field projectsWillNotBeDeleted  integer Number of projects that will not be deleted.
#'
#' @field usersWillBeDeleted  integer Number of users that will be deleted.
#'
#' @field usersWillNotBeDeleted  integer Number of users that will not be deleted.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UsersPermadeletePreviewStatistics <- R6::R6Class(
  "UsersPermadeletePreviewStatistics",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(deploymentsWillBeAssignedNewOwner = NULL, deploymentsWillBeDeleted = NULL, deploymentsWillNotBeDeleted = NULL, errors = NULL, projectsWillBeAssignedNewOwner = NULL, projectsWillBeDeleted = NULL, projectsWillNotBeDeleted = NULL, usersWillBeDeleted = NULL, usersWillNotBeDeleted = NULL) {
      if (!is.null(`deploymentsWillBeAssignedNewOwner`)) {
        stopifnot(is.numeric(`deploymentsWillBeAssignedNewOwner`), length(`deploymentsWillBeAssignedNewOwner`) == 1)
      }
      if (!is.null(`deploymentsWillBeDeleted`)) {
        stopifnot(is.numeric(`deploymentsWillBeDeleted`), length(`deploymentsWillBeDeleted`) == 1)
      }
      if (!is.null(`deploymentsWillNotBeDeleted`)) {
        stopifnot(is.numeric(`deploymentsWillNotBeDeleted`), length(`deploymentsWillNotBeDeleted`) == 1)
      }
      if (!is.null(`errors`)) {
        stopifnot(is.numeric(`errors`), length(`errors`) == 1)
      }
      if (!is.null(`projectsWillBeAssignedNewOwner`)) {
        stopifnot(is.numeric(`projectsWillBeAssignedNewOwner`), length(`projectsWillBeAssignedNewOwner`) == 1)
      }
      if (!is.null(`projectsWillBeDeleted`)) {
        stopifnot(is.numeric(`projectsWillBeDeleted`), length(`projectsWillBeDeleted`) == 1)
      }
      if (!is.null(`projectsWillNotBeDeleted`)) {
        stopifnot(is.numeric(`projectsWillNotBeDeleted`), length(`projectsWillNotBeDeleted`) == 1)
      }
      if (!is.null(`usersWillBeDeleted`)) {
        stopifnot(is.numeric(`usersWillBeDeleted`), length(`usersWillBeDeleted`) == 1)
      }
      if (!is.null(`usersWillNotBeDeleted`)) {
        stopifnot(is.numeric(`usersWillNotBeDeleted`), length(`usersWillNotBeDeleted`) == 1)
      }
    }
  ),
  public = list(
    `deploymentsWillBeAssignedNewOwner` = NULL,
    `deploymentsWillBeDeleted` = NULL,
    `deploymentsWillNotBeDeleted` = NULL,
    `errors` = NULL,
    `projectsWillBeAssignedNewOwner` = NULL,
    `projectsWillBeDeleted` = NULL,
    `projectsWillNotBeDeleted` = NULL,
    `usersWillBeDeleted` = NULL,
    `usersWillNotBeDeleted` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param deploymentsWillBeAssignedNewOwner Number of deployments that will be assigned a new owner.
    #' @param deploymentsWillBeDeleted Number of deployments that will be deleted.
    #' @param deploymentsWillNotBeDeleted Number of deployments that will not be deleted.
    #' @param errors Number of errors encountered during preview construction.
    #' @param projectsWillBeAssignedNewOwner Number of projects that will be assigned a new owner.
    #' @param projectsWillBeDeleted Number of projects that will be deleted.
    #' @param projectsWillNotBeDeleted Number of projects that will not be deleted.
    #' @param usersWillBeDeleted Number of users that will be deleted.
    #' @param usersWillNotBeDeleted Number of users that will not be deleted.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`deploymentsWillBeAssignedNewOwner` = NULL, `deploymentsWillBeDeleted` = NULL, `deploymentsWillNotBeDeleted` = NULL, `errors` = NULL, `projectsWillBeAssignedNewOwner` = NULL, `projectsWillBeDeleted` = NULL, `projectsWillNotBeDeleted` = NULL, `usersWillBeDeleted` = NULL, `usersWillNotBeDeleted` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`deploymentsWillBeAssignedNewOwner`, `deploymentsWillBeDeleted`, `deploymentsWillNotBeDeleted`, `errors`, `projectsWillBeAssignedNewOwner`, `projectsWillBeDeleted`, `projectsWillNotBeDeleted`, `usersWillBeDeleted`, `usersWillNotBeDeleted`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(deploymentsWillBeAssignedNewOwner, deploymentsWillBeDeleted, deploymentsWillNotBeDeleted, errors, projectsWillBeAssignedNewOwner, projectsWillBeDeleted, projectsWillNotBeDeleted, usersWillBeDeleted, usersWillNotBeDeleted)
      }
      self$`deploymentsWillBeAssignedNewOwner` <- `deploymentsWillBeAssignedNewOwner`
      self$`deploymentsWillBeDeleted` <- `deploymentsWillBeDeleted`
      self$`deploymentsWillNotBeDeleted` <- `deploymentsWillNotBeDeleted`
      self$`errors` <- `errors`
      self$`projectsWillBeAssignedNewOwner` <- `projectsWillBeAssignedNewOwner`
      self$`projectsWillBeDeleted` <- `projectsWillBeDeleted`
      self$`projectsWillNotBeDeleted` <- `projectsWillNotBeDeleted`
      self$`usersWillBeDeleted` <- `usersWillBeDeleted`
      self$`usersWillNotBeDeleted` <- `usersWillNotBeDeleted`
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(deploymentsWillBeAssignedNewOwner = self$`deploymentsWillBeAssignedNewOwner`, deploymentsWillBeDeleted = self$`deploymentsWillBeDeleted`, deploymentsWillNotBeDeleted = self$`deploymentsWillNotBeDeleted`, errors = self$`errors`, projectsWillBeAssignedNewOwner = self$`projectsWillBeAssignedNewOwner`, projectsWillBeDeleted = self$`projectsWillBeDeleted`, projectsWillNotBeDeleted = self$`projectsWillNotBeDeleted`, usersWillBeDeleted = self$`usersWillBeDeleted`, usersWillNotBeDeleted = self$`usersWillNotBeDeleted`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`deploymentsWillBeAssignedNewOwner`)) {
          sprintf(
            '"deploymentsWillBeAssignedNewOwner":
            %d
                  ',
            self$`deploymentsWillBeAssignedNewOwner`
          )
        },
        if (!is.null(self$`deploymentsWillBeDeleted`)) {
          sprintf(
            '"deploymentsWillBeDeleted":
            %d
                  ',
            self$`deploymentsWillBeDeleted`
          )
        },
        if (!is.null(self$`deploymentsWillNotBeDeleted`)) {
          sprintf(
            '"deploymentsWillNotBeDeleted":
            %d
                  ',
            self$`deploymentsWillNotBeDeleted`
          )
        },
        if (!is.null(self$`errors`)) {
          sprintf(
            '"errors":
            %d
                  ',
            self$`errors`
          )
        },
        if (!is.null(self$`projectsWillBeAssignedNewOwner`)) {
          sprintf(
            '"projectsWillBeAssignedNewOwner":
            %d
                  ',
            self$`projectsWillBeAssignedNewOwner`
          )
        },
        if (!is.null(self$`projectsWillBeDeleted`)) {
          sprintf(
            '"projectsWillBeDeleted":
            %d
                  ',
            self$`projectsWillBeDeleted`
          )
        },
        if (!is.null(self$`projectsWillNotBeDeleted`)) {
          sprintf(
            '"projectsWillNotBeDeleted":
            %d
                  ',
            self$`projectsWillNotBeDeleted`
          )
        },
        if (!is.null(self$`usersWillBeDeleted`)) {
          sprintf(
            '"usersWillBeDeleted":
            %d
                  ',
            self$`usersWillBeDeleted`
          )
        },
        if (!is.null(self$`usersWillNotBeDeleted`)) {
          sprintf(
            '"usersWillNotBeDeleted":
            %d
                  ',
            self$`usersWillNotBeDeleted`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param UsersPermadeletePreviewStatisticsJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(UsersPermadeletePreviewStatisticsJson, validateParams = FALSE) {
      UsersPermadeletePreviewStatisticsObject <- jsonlite::fromJSON(UsersPermadeletePreviewStatisticsJson)
      self$`deploymentsWillBeAssignedNewOwner` <- UsersPermadeletePreviewStatisticsObject$`deploymentsWillBeAssignedNewOwner`
      self$`deploymentsWillBeDeleted` <- UsersPermadeletePreviewStatisticsObject$`deploymentsWillBeDeleted`
      self$`deploymentsWillNotBeDeleted` <- UsersPermadeletePreviewStatisticsObject$`deploymentsWillNotBeDeleted`
      self$`errors` <- UsersPermadeletePreviewStatisticsObject$`errors`
      self$`projectsWillBeAssignedNewOwner` <- UsersPermadeletePreviewStatisticsObject$`projectsWillBeAssignedNewOwner`
      self$`projectsWillBeDeleted` <- UsersPermadeletePreviewStatisticsObject$`projectsWillBeDeleted`
      self$`projectsWillNotBeDeleted` <- UsersPermadeletePreviewStatisticsObject$`projectsWillNotBeDeleted`
      self$`usersWillBeDeleted` <- UsersPermadeletePreviewStatisticsObject$`usersWillBeDeleted`
      self$`usersWillNotBeDeleted` <- UsersPermadeletePreviewStatisticsObject$`usersWillNotBeDeleted`

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
