# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.28.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UserBlueprintAddToMenu
#'
#' @description UserBlueprintAddToMenu Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field deleteAfter  character Whether to delete the user blueprint(s) after adding it (them) to the project menu.
#'
#' @field describeFailures  character Whether to include extra fields to describe why any blueprints were not added to the chosen project.
#'
#' @field projectId  character The projectId of the project for the repository to add the specified user blueprints to.
#'
#' @field userBlueprintIds  list( character ) The ids of the user blueprints to add to the specified project&#39;s repository.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserBlueprintAddToMenu <- R6::R6Class(
  "UserBlueprintAddToMenu",
  lock_objects = FALSE,
  private = list(
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(deleteAfter = NULL, describeFailures = NULL, projectId = NULL, userBlueprintIds = NULL) {
      if (!is.null(`deleteAfter`)) {
        stopifnot(is.logical(`deleteAfter`), length(`deleteAfter`) == 1)
      }
      if (!is.null(`describeFailures`)) {
        stopifnot(is.logical(`describeFailures`), length(`describeFailures`) == 1)
      }
      if (!is.null(`projectId`)) {
        stopifnot(is.character(`projectId`), length(`projectId`) == 1)
      }
      if (!is.null(`userBlueprintIds`)) {
        stopifnot(is.vector(`userBlueprintIds`))
      }
    }
  ),
  public = list(
    `deleteAfter` = NULL,
    `describeFailures` = NULL,
    `projectId` = NULL,
    `userBlueprintIds` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param deleteAfter Whether to delete the user blueprint(s) after adding it (them) to the project menu.
    #' @param describeFailures Whether to include extra fields to describe why any blueprints were not added to the chosen project.
    #' @param projectId The projectId of the project for the repository to add the specified user blueprints to.
    #' @param userBlueprintIds The ids of the user blueprints to add to the specified project&#39;s repository.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`deleteAfter` = NULL, `describeFailures` = NULL, `projectId` = NULL, `userBlueprintIds` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      requiredProps <- list(`deleteAfter`, `describeFailures`, `projectId`, `userBlueprintIds`)
      if (validateParams) {
        lapply(requiredProps, missing)
        private$validateProps(deleteAfter, describeFailures, projectId, userBlueprintIds)
      }
      self$`deleteAfter` <- `deleteAfter`
      self$`describeFailures` <- `describeFailures`
      self$`projectId` <- `projectId`
      sapply(`userBlueprintIds`, function(x) stopifnot(is.character(x)))
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    validate = function() {
      props <- list(deleteAfter = self$`deleteAfter`, describeFailures = self$`describeFailures`, projectId = self$`projectId`, userBlueprintIds = self$`userBlueprintIds`)
      do.call(private$validateProps, props)
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`deleteAfter`)) {
          sprintf(
            '"deleteAfter":
            %s
                  ',
            tolower(self$`deleteAfter`)
          )
        },
        if (!is.null(self$`describeFailures`)) {
          sprintf(
            '"describeFailures":
            %s
                  ',
            tolower(self$`describeFailures`)
          )
        },
        if (!is.null(self$`projectId`)) {
          sprintf(
            '"projectId":
            "%s"
                  ',
            self$`projectId`
          )
        },
        if (!is.null(self$`userBlueprintIds`)) {
          sprintf(
            '"userBlueprintIds":
              [%s]
            ',
            paste(unlist(lapply(self$`userBlueprintIds`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param UserBlueprintAddToMenuJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(UserBlueprintAddToMenuJson, validateParams = FALSE) {
      UserBlueprintAddToMenuObject <- jsonlite::fromJSON(UserBlueprintAddToMenuJson)
      self$`deleteAfter` <- UserBlueprintAddToMenuObject$`deleteAfter`
      self$`describeFailures` <- UserBlueprintAddToMenuObject$`describeFailures`
      self$`projectId` <- UserBlueprintAddToMenuObject$`projectId`
      self$`userBlueprintIds` <- ApiClient$new()$deserializeObj(UserBlueprintAddToMenuObject$`userBlueprintIds`, "array[character]", loadNamespace("datarobot.apicore"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
