# Copyright 2021-2022 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# DataRobot, Inc.
#
# This is proprietary source code of DataRobot, Inc. and its
# affiliates.

# Public API
#
# DataRobot's Public facing API
#
# The version of the OpenAPI document: 2.29.0
# Contact: api-maintainer@datarobot.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VertexContextItemMessages
#'
#' @description VertexContextItemMessages Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field errors  list( character ) [optional] Errors with a specific vertex in the blueprint. Execution of the vertex is expected to fail.
#'
#' @field warnings  list( character ) [optional] Warnings about a specific vertex in the blueprint. Execution of the vertex may fail or behave unexpectedly.
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VertexContextItemMessages <- R6::R6Class(
  "VertexContextItemMessages",
  lock_objects = FALSE,
  private = list(
    # @description The properties of this object that are required to be set.
    # @description A helper function to handle assist with type validation. This function will validate class parameters with definite
    # types assigned to them, as well as handling validation of parameters with anyOf and oneOf types listed. These types
    # can themselves be other R6 objects.
    validateProps = function(`errors` = NULL, `warnings` = NULL) {
      if (!is.null(`errors`)) {
        stopifnot(is.vector(`errors`))
      }
      if (!is.null(`warnings`)) {
        stopifnot(is.vector(`warnings`))
      }
    }
  ),
  public = list(
    `errors` = NULL,
    `warnings` = NULL,
    #' @description A function used to initialize an instance of this class.
    #' @param errors Errors with a specific vertex in the blueprint. Execution of the vertex is expected to fail.
    #' @param warnings Warnings about a specific vertex in the blueprint. Execution of the vertex may fail or behave unexpectedly.
    #' @param validateParams An optional param for auto validating this object's parameters before initialization. Default FALSE.
    #' @param ... Any additional keyword arguments to be passed into this object for initialization.
    initialize = function(`errors` = NULL, `warnings` = NULL, validateParams = FALSE, ...) {
      local.optional.var <- list(...)
      if (validateParams) {
        lapply(list(), function(param) {
          stopifnot("Required param not set." = !is.null(param))
        })
        private$validateProps(errors, warnings)
      }
      sapply(`errors`, function(x) stopifnot(is.character(x)))
      sapply(`warnings`, function(x) stopifnot(is.character(x)))
    },
    #' @description A helper function that provides public access to the private validateProps function. This allows users the ability
    #' to programmatically validate objects before sending them to DataRobot.
    #' checking this objects set properties.
    validate = function() {
      do.call(private$validateProps, list(errors = self$`errors`, warnings = self$`warnings`))
    },
    #' @description A helper function that serializes this object into a JSON encoded string.
    toJSON = function() {
      jsoncontent <- c(
        if (!is.null(self$`errors`)) {
          sprintf(
            '"errors":
            [%s]
                  ',
            paste(unlist(lapply(self$`errors`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        },
        if (!is.null(self$`warnings`)) {
          sprintf(
            '"warnings":
            [%s]
                  ',
            paste(unlist(lapply(self$`warnings`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste("{", jsoncontent, "}", sep = "")
    },
    #' @description A helper function that deserializes a JSON string into an instance of this class.
    #' @param VertexContextItemMessagesJson A JSON encoded string representation of a class instance.
    #' @param validateParams An optional param for auto validating this object's parameters after deserialization. Default FALSE.
    fromJSON = function(VertexContextItemMessagesJson, validateParams = FALSE) {
      VertexContextItemMessagesObject <- jsonlite::fromJSON(VertexContextItemMessagesJson)
      self$`errors` <- ApiClient$new()$deserializeObj(VertexContextItemMessagesObject$`errors`, "array[character]", loadNamespace("datarobot.apicore"))
      self$`warnings` <- ApiClient$new()$deserializeObj(VertexContextItemMessagesObject$`warnings`, "array[character]", loadNamespace("datarobot.apicore"))

      if (validateParams) {
        self$validate()
      }

      return(self)
    }
  )
)
